/**
 * Turn the round-4 live probes into fixture modules.
 *
 * These are the round that `forwardSubagentText` opened up: `fwd` is ONE agent
 * whose whole conversation is forwarded while it runs — the probe that proves
 * an agent view can be live rather than only complete — `fwd2` is a nested
 * agent tree whose FULL conversations are on the wire (text and thinking
 * forwarded with `parent_tool_use_id`), and `relay` is a message reaching a
 * running background agent through main's SendMessage.
 *
 * Same envelope shape and same exclusions as the round-3 generator — inbound
 * protocol lines only, minus our own handshake reply and the CLI's lifecycle
 * chatter — so the two fixture families are byte-comparable.
 *
 *   bun run scripts/generate-round4-fixtures.ts /tmp/harness-build/round3
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const sourceDir = process.argv[2] ?? "/tmp/harness-build/round3";
const outDir = resolve(import.meta.dir, "../src/dev/fixtures");

const NAMES = ["fwd", "fwd2", "relay"] as const;

for (const name of NAMES) {
  const raw = readFileSync(resolve(sourceDir, `${name}.jsonl`), "utf8");
  const kept: string[] = [];
  for (const row of raw.split("\n")) {
    const trimmed = row.trim();
    if (!trimmed) continue;
    const envelope = JSON.parse(trimmed) as { dir?: string; line?: unknown };
    if (envelope.dir !== "in") continue;
    const line = envelope.line;
    if (typeof line !== "object" || line === null) continue;
    const type = (line as { type?: string }).type;
    if (type === "control_response" || type === "command_lifecycle" || type === "keep_alive") {
      continue;
    }
    kept.push(JSON.stringify(line));
  }
  const constant = `${name}Round4Raw`;
  const body = `// GENERATED by scripts/generate-round4-fixtures.ts from live probe ${name}.jsonl
// (claude CLI 2.1.233, forwardSubagentText). Do not hand-edit; re-run the generator.
export const ${constant} = ${JSON.stringify(kept.join("\n"))};
`;
  writeFileSync(resolve(outDir, `round4${name[0].toUpperCase()}${name.slice(1)}Raw.ts`), body, "utf8");
  process.stdout.write(`${name}: ${kept.length} lines, ${(body.length / 1024).toFixed(1)} KB\n`);
}
