/**
 * Turn the round-3 live probes into fixture modules.
 *
 * The probes are recorded as `{t, dir, line}` envelopes carrying BOTH directions
 * plus stderr rows; only the inbound protocol lines belong in a fixture. The
 * `control_response` answering our `initialize` is dropped as well — it is 29KB
 * of model catalog per probe, and `initializeResponse()` in build.ts already
 * supplies the same shape to every other fixture.
 *
 *   bun run scripts/generate-round3-fixtures.ts /tmp/harness-build/round3
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const sourceDir = process.argv[2] ?? "/tmp/harness-build/round3";
const outDir = resolve(import.meta.dir, "../src/dev/fixtures");

const NAMES = ["shells", "nested", "workflow", "bg"] as const;

for (const name of NAMES) {
  const raw = readFileSync(resolve(sourceDir, `${name}.jsonl`), "utf8");
  const kept: string[] = [];
  for (const row of raw.split("\n")) {
    const trimmed = row.trim();
    if (!trimmed) continue;
    const envelope = JSON.parse(trimmed) as { dir?: string; line?: unknown };
    if (envelope.dir !== "in") continue;
    const line = envelope.line;
    if (typeof line !== "object" || line === null) continue;
    const type = (line as { type?: string }).type;
    // Our own handshake reply and the CLI's internal lifecycle chatter: neither
    // is something the reducer is meant to render.
    if (type === "control_response" || type === "command_lifecycle" || type === "keep_alive") {
      continue;
    }
    kept.push(JSON.stringify(line));
  }
  const constant = `${name}Round3Raw`;
  const body = `// GENERATED by scripts/generate-round3-fixtures.ts from live probe ${name}.jsonl
// (claude CLI 2.1.233). Do not hand-edit; re-run the generator instead.
export const ${constant} = ${JSON.stringify(kept.join("\n"))};
`;
  writeFileSync(resolve(outDir, `round3${name[0].toUpperCase()}${name.slice(1)}Raw.ts`), body, "utf8");
  process.stdout.write(`${name}: ${kept.length} lines, ${(body.length / 1024).toFixed(1)} KB\n`);
}
