import CmuxComputerUseCore

typealias ComputerUseOnboardingCompletion = CmuxComputerUseCore.ComputerUseOnboardingCompletion
typealias ComputerUseRuntimePermissionPhase = CmuxComputerUseCore.ComputerUseRuntimePermissionPhase
typealias ComputerUseDirectScreenCaptureVerification = CmuxComputerUseCore.ComputerUseDirectScreenCaptureVerification
typealias ComputerUseHelperIdentity = CmuxComputerUseCore.ComputerUseHelperIdentity
typealias ComputerUseOnboardingStore = CmuxComputerUseCore.ComputerUseOnboardingStore
