import { describe, expect, test } from "bun:test";
import { classifyLocalUserText, stripAnsi } from "../src/model/localText";
import {
  applyLine,
  applyLocalAction,
  createIndex,
  createModel,
  replayLines
} from "../src/model/transcript";
import type { Block, TranscriptModel, Turn } from "../src/model/types";
import type { ProtocolLine } from "../src/protocol/types";

/**
 * Synthetic fixtures mirroring the REAL records in
 * ~/.claude/projects/-Users-syedrajin-Documents-ryne/f9a177ef….jsonl — the
 * session whose resume produced the round-5 screenshot (raw XML bubbles, the
 * "GPT 5.6 Sol" trigger). Shapes verified against the file; content invented.
 */

let seq = 0;
const uid = (p: string) => `${p}-${(seq += 1).toString(16).padStart(4, "0")}`;

function diskUser(content: string, at: string, extra: Record<string, unknown> = {}): ProtocolLine {
  return {
    type: "user",
    message: { role: "user", content },
    parent_tool_use_id: null,
    session_id: "ryne-mirror",
    uuid: uid("user"),
    timestamp: at,
    ...extra
  } as ProtocolLine;
}

function diskAssistant(text: string, model: string, at: string): ProtocolLine {
  return {
    type: "assistant",
    message: {
      id: uid("msg"),
      model,
      role: "assistant",
      content: [{ type: "text", text }]
    },
    parent_tool_use_id: null,
    session_id: "ryne-mirror",
    uuid: uid("asst"),
    timestamp: at
  } as ProtocolLine;
}

const CAVEAT =
  "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";

/** Root-to-leaf replay of a session that ran /model repeatedly, as on disk. */
function ryneMirror(): ProtocolLine[] {
  return [
    diskUser("find the loading spinner asset", "2026-08-18T19:21:15.611Z"),
    diskAssistant("Found it — it is a CSS mask animation.", "gpt-5.6-sol", "2026-08-18T19:22:29.105Z"),
    // NOTE: the caveat records are `isMeta: true` on disk, but the harness
    // mapper forwards user records regardless — the classifier must hide them
    // even if the flag were dropped, so the fixture omits the flag on one.
    diskUser(CAVEAT, "2026-08-18T19:26:02.562Z", { isMeta: true }),
    diskUser(
      "<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>opus[1m]</command-args>",
      "2026-08-18T19:26:02.562Z"
    ),
    diskUser(
      "<local-command-stdout>Set model to opus[1m] (claude-opus-5[1m])</local-command-stdout>",
      "2026-08-18T19:26:02.562Z"
    ),
    diskUser("thanks", "2026-08-18T19:26:08.853Z"),
    diskAssistant("You're welcome.", "claude-opus-5", "2026-08-18T19:26:11.600Z")
  ];
}

function allBlocks(model: TranscriptModel): Block[] {
  const out: Block[] = [];
  const visit = (blocks: Block[]) => {
    for (const block of blocks) {
      out.push(block);
      if (block.kind === "tool") visit(block.children);
    }
  };
  for (const turn of model.turns) visit(turn.blocks);
  return out;
}

/** Every string a turn can paint: user text, command chip, block texts. */
function renderedStrings(model: TranscriptModel): string[] {
  const out: string[] = [];
  for (const turn of model.turns) {
    if (turn.userText) out.push(turn.userText);
    if (turn.command) out.push(turn.command.name, turn.command.args ?? "");
  }
  for (const block of allBlocks(model)) {
    if ("text" in block && typeof block.text === "string") out.push(block.text);
  }
  return out;
}

describe("classifyLocalUserText", () => {
  test("recognises the command record and strips nothing from literal [1m] selectors", () => {
    expect(
      classifyLocalUserText(
        "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus[1m]</command-args>"
      )
    ).toEqual({ kind: "command", name: "/model", args: "opus[1m]" });
  });

  test("keeps literal [1m] in stdout but strips real ANSI sequences", () => {
    const esc = String.fromCharCode(27);
    expect(stripAnsi("Set model to opus[1m]")).toBe("Set model to opus[1m]");
    expect(stripAnsi(`${esc}[2mCompacted${esc}[0m`)).toBe("Compacted");
    expect(
      classifyLocalUserText(
        `<local-command-stdout>${esc}[2mCompacted conversation${esc}[0m</local-command-stdout>`
      )
    ).toEqual({ kind: "commandOutput", text: "Compacted conversation" });
  });

  test("hides caveat scaffolding, skill payloads, task notifications, system reminders, and empty stdout", () => {
    expect(classifyLocalUserText(CAVEAT).kind).toBe("hidden");
    expect(
      classifyLocalUserText(
        "Base directory for this skill: /tmp/example/.claude/skills/cmux-testing\n\n# cmux Testing\n\nInternal skill instructions"
      ).kind
    ).toBe("hidden");
    expect(classifyLocalUserText("<task-notification>\n<task-id>x</task-id>").kind).toBe("hidden");
    expect(classifyLocalUserText("<system-reminder>internal guidance</system-reminder>").kind).toBe(
      "hidden"
    );
    expect(classifyLocalUserText("<local-command-stdout></local-command-stdout>").kind).toBe(
      "hidden"
    );
  });

  test("classifies interrupts and compact continuations", () => {
    expect(classifyLocalUserText("[Request interrupted by user]").kind).toBe("interrupt");
    expect(classifyLocalUserText("[Request interrupted by user for tool use]").kind).toBe(
      "interrupt"
    );
    expect(
      classifyLocalUserText(
        "This session is being continued from a previous conversation that ran out of context…"
      ).kind
    ).toBe("continued");
  });

  test("handles the older tag order (<command-message> first) seen in real mission sessions", () => {
    expect(
      classifyLocalUserText(
        "<command-message>mission-run</command-message>\n<command-name>/mission-run</command-name>"
      )
    ).toEqual({ kind: "command", name: "/mission-run", args: undefined });
  });

  test("leaves ordinary messages alone — including ones that merely contain XML", () => {
    expect(classifyLocalUserText("hello").kind).toBe("plain");
    expect(classifyLocalUserText("why does <command-name> render raw?").kind).toBe("plain");
  });
});

describe("resuming a session with /model history (round-5 screenshot)", () => {
  const model = replayLines(ryneMirror());

  test("no raw command XML survives anywhere in the rendered model", () => {
    for (const text of renderedStrings(model)) {
      expect(text).not.toContain("<command-name>");
      expect(text).not.toContain("<command-message>");
      expect(text).not.toContain("<command-args>");
      expect(text).not.toContain("<local-command-stdout>");
      expect(text).not.toContain("<local-command-caveat>");
    }
  });

  test("the /model invocation is a command chip, not a user bubble", () => {
    const command = model.turns.find((t) => t.command);
    expect(command).toBeDefined();
    expect(command!.command).toEqual({ name: "/model", args: "opus[1m]" });
    expect(command!.userText).toBeUndefined();
    // Born complete: no result frame will ever settle a local command.
    expect(command!.state).toBe("complete");
  });

  test("its stdout is a dim commandOutput line under the chip, not a bubble", () => {
    const command = model.turns.find((t) => t.command)!;
    const output = command.blocks.find((b) => b.kind === "commandOutput");
    expect(output).toBeDefined();
    expect(output!.kind === "commandOutput" && output!.text).toBe(
      "Set model to opus[1m] (claude-opus-5[1m])"
    );
  });

  test("the caveat preamble is hidden entirely", () => {
    expect(model.turns.some((t) => t.userText?.includes("Caveat"))).toBe(false);
  });

  test("real user turns and assistant answers still land as themselves", () => {
    const users = model.turns.filter((t) => t.userText !== undefined).map((t) => t.userText);
    expect(users).toEqual(["find the loading spinner asset", "thanks"]);
  });

  test("assistant output after a command chip opens a NEW turn — never reopens the chip", () => {
    const commandIndex = model.turns.findIndex((t) => t.command);
    const command = model.turns[commandIndex];
    expect(command.blocks.some((b) => b.kind === "text")).toBe(false);
  });

  test("even with NO user message in between (a prompt-carrying command like /mission-run)", () => {
    // The headball mission sessions: the command record is followed directly by
    // the assistant's work. `ensureTurn`'s reopen heuristic must not merge that
    // work INTO the completed chip turn.
    const index = createIndex();
    let m = createModel();
    m = applyLine(
      m,
      index,
      diskUser(
        "<command-message>mission-run</command-message>\n<command-name>/mission-run</command-name>",
        "2026-08-14T09:00:00.000Z"
      ),
      Date.now()
    );
    m = applyLine(
      m,
      index,
      diskAssistant("Kicking off the mission.", "claude-fable-5", "2026-08-14T09:00:10.000Z"),
      Date.now()
    );
    expect(m.turns.length).toBe(2);
    expect(m.turns[0].command).toEqual({ name: "/mission-run", args: undefined });
    expect(m.turns[0].blocks.some((b) => b.kind === "text")).toBe(false);
    expect(m.turns[1].blocks.some((b) => b.kind === "text")).toBe(true);
  });

  test("the replayed session's actual model is recorded off its last main assistant frame", () => {
    expect(model.lastAssistantModel).toBe("claude-opus-5");
  });
});

describe("historyReplayed — settling a drained replay", () => {
  function replayedOpen(): { model: TranscriptModel; index: ReturnType<typeof createIndex> } {
    const index = createIndex();
    let model = createModel();
    // A session whose recording ends mid-answer: last frame is assistant text,
    // no result. Exactly what loadSessionHistory hands back.
    model = applyLine(model, index, diskUser("audit the pane", "2026-08-16T10:00:00.000Z"), Date.now());
    model = applyLine(
      model,
      index,
      diskAssistant("Working on it.", "claude-opus-5", "2026-08-16T10:00:41.000Z"),
      Date.now()
    );
    return { model, index };
  }

  test("closes the replayed open turn as COMPLETE, not error", () => {
    const { model, index } = replayedOpen();
    expect(model.turns[0].state).toBe("streaming");
    const settled = applyLocalAction(model, index, { kind: "historyReplayed" }, Date.now());
    expect(settled.turns[0].state).toBe("complete");
    expect(settled.activity.sessionState).toBe("idle");
  });

  test("ends the turn at its own last frame, not at wall-now — no 2-day 'Worked for'", () => {
    const { model, index } = replayedOpen();
    const settled = applyLocalAction(model, index, { kind: "historyReplayed" }, Date.now());
    const turn = settled.turns[0];
    expect(turn.endedAtMs).toBe(Date.parse("2026-08-16T10:00:41.000Z"));
    expect(turn.startedAtMs).toBe(Date.parse("2026-08-16T10:00:00.000Z"));
    expect(turn.endedAtMs! - turn.startedAtMs).toBe(41000);
  });

  test("adopts the replayed session's model so the trigger reflects it before any init frame", () => {
    const { model, index } = replayedOpen();
    expect(model.session.model).toBeUndefined();
    const settled = applyLocalAction(model, index, { kind: "historyReplayed" }, Date.now());
    expect(settled.session.model).toBe("claude-opus-5");
  });

  test("a runStarted AFTER historyReplayed no longer flips history to 'Failed after…'", () => {
    const { model, index } = replayedOpen();
    let next = applyLocalAction(model, index, { kind: "historyReplayed" }, Date.now());
    const { applyEvent } = require("../src/model/transcript") as typeof import("../src/model/transcript");
    next = applyEvent(next, index, { kind: "runStarted", runId: "r2" }, Date.now());
    expect(next.turns[0].state).toBe("complete");
  });
});

describe("replayed interrupt markers", () => {
  test("'[Request interrupted by user]' aborts the open turn instead of rendering a bubble", () => {
    const index = createIndex();
    let model = createModel();
    model = applyLine(model, index, diskUser("do the thing", "2026-08-16T11:00:00.000Z"), Date.now());
    model = applyLine(
      model,
      index,
      diskAssistant("Starting…", "claude-opus-5", "2026-08-16T11:00:05.000Z"),
      Date.now()
    );
    model = applyLine(
      model,
      index,
      {
        type: "user",
        message: { role: "user", content: [{ type: "text", text: "[Request interrupted by user]" }] },
        parent_tool_use_id: null,
        session_id: "ryne-mirror",
        uuid: uid("int"),
        timestamp: "2026-08-16T11:00:09.000Z"
      } as ProtocolLine,
      Date.now()
    );
    expect(model.turns.length).toBe(1);
    expect(model.turns[0].state).toBe("aborted");
    expect(model.turns[0].endedAtMs).toBe(Date.parse("2026-08-16T11:00:09.000Z"));
    expect(renderedStrings(model).some((t) => t.includes("[Request interrupted"))).toBe(false);
  });
});

describe("replayed compact continuation", () => {
  test("the machine-written summary renders as a divider, not a giant user bubble", () => {
    const summary =
      "This session is being continued from a previous conversation that ran out of context. The conversation is summarized below:\nAnalysis:\n…3000 words…";
    const index = createIndex();
    let model = createModel();
    model = applyLine(model, index, diskUser(summary, "2026-08-16T12:00:00.000Z"), Date.now());
    model = applyLine(
      model,
      index,
      diskAssistant("Picking up where we left off.", "claude-opus-5", "2026-08-16T12:00:07.000Z"),
      Date.now()
    );
    expect(model.turns.length).toBe(1);
    const turn = model.turns[0];
    expect(turn.userText).toBeUndefined();
    const divider = turn.blocks.find((b) => b.kind === "divider");
    expect(divider).toBeDefined();
    expect(divider!.kind === "divider" && divider!.variant).toBe("continued");
    // The continuation's own answer still lands in the turn.
    expect(turn.blocks.some((b) => b.kind === "text")).toBe(true);
  });
});

describe("replayed task notifications", () => {
  test("'<task-notification>…' user records are hidden — they are wire plumbing", () => {
    const index = createIndex();
    let model = createModel();
    model = applyLine(model, index, diskUser("run the workflow", "2026-08-18T20:43:31.227Z"), Date.now());
    model = applyLine(
      model,
      index,
      diskUser(
        "<task-notification>\n<task-id>whyrxn8k3</task-id>\n<tool-use-id>call_x</tool-use-id>\n<status>completed</status>",
        "2026-08-18T20:44:05.963Z"
      ),
      Date.now()
    );
    expect(model.turns.length).toBe(1);
    expect(renderedStrings(model).some((t) => t.includes("task-notification"))).toBe(false);
  });
});

describe("live local_command_output frames", () => {
  test("render as the same dim commandOutput line the replay path draws — one rendering for both", () => {
    const index = createIndex();
    let model = createModel();
    model = applyLine(model, index, diskUser("hello", "2026-08-18T19:21:15.611Z"), Date.now());
    model = applyLine(
      model,
      index,
      {
        type: "system",
        subtype: "local_command_output",
        content: "Set model to opus[1m] (claude-opus-5[1m])",
        uuid: uid("lco")
      } as ProtocolLine,
      Date.now()
    );
    const turn = model.turns[model.turns.length - 1];
    const output = turn.blocks.find((b) => b.kind === "commandOutput");
    expect(output).toBeDefined();
    expect(output!.kind === "commandOutput" && output!.text).toBe(
      "Set model to opus[1m] (claude-opus-5[1m])"
    );
    expect(turn.blocks.some((b) => b.kind === "notice")).toBe(false);
  });
});

/** A turn's timestamps come from the records themselves on replay. */
describe("replayed turn timing", () => {
  test("turn start and lastFrame track record timestamps", () => {
    const model = replayLines(ryneMirror());
    const first = model.turns[0] as Turn;
    expect(first.startedAtMs).toBe(Date.parse("2026-08-18T19:21:15.611Z"));
    expect(first.lastFrameAtMs).toBe(Date.parse("2026-08-18T19:22:29.105Z"));
  });
});
