import Foundation

/// English copy for the harness web UI; every key mirrors harness-web/src/copyKeys.ts.
enum SupermuxHarnessCopy {
    static func dictionary() -> [String: String] {
        [
            "supermux.harness.app.untitledSession": String(localized: "supermux.harness.app.untitledSession", defaultValue: "New session"),
            "supermux.harness.empty.headline": String(localized: "supermux.harness.empty.headline", defaultValue: "Claude Code, in your workspace"),
            "supermux.harness.empty.subhead": String(localized: "supermux.harness.empty.subhead", defaultValue: "Ask a question, describe a change, or paste an error."),
            "supermux.harness.empty.workingIn": String(localized: "supermux.harness.empty.workingIn", defaultValue: "Working in"),
            "supermux.harness.empty.recentSessions": String(localized: "supermux.harness.empty.recentSessions", defaultValue: "Recent sessions"),
            "supermux.harness.empty.suggestionsTitle": String(localized: "supermux.harness.empty.suggestionsTitle", defaultValue: "Try one of these"),
            "supermux.harness.empty.suggestion1": String(localized: "supermux.harness.empty.suggestion1", defaultValue: "Explain how this project is structured"),
            "supermux.harness.empty.suggestion2": String(localized: "supermux.harness.empty.suggestion2", defaultValue: "Find and fix the failing test"),
            "supermux.harness.empty.suggestion3": String(localized: "supermux.harness.empty.suggestion3", defaultValue: "Review my uncommitted changes"),
            "supermux.harness.empty.detectingModel": String(localized: "supermux.harness.empty.detectingModel", defaultValue: "Detecting model…"),
            "supermux.harness.nocli.headline": String(localized: "supermux.harness.nocli.headline", defaultValue: "Claude Code CLI not found"),
            "supermux.harness.nocli.body": String(localized: "supermux.harness.nocli.body", defaultValue: "This pane drives the Claude Code command-line tool. Install it, then retry."),
            "supermux.harness.nocli.install": String(localized: "supermux.harness.nocli.install", defaultValue: "npm install -g @anthropic-ai/claude-code"),
            "supermux.harness.nocli.retry": String(localized: "supermux.harness.nocli.retry", defaultValue: "Retry detection"),
            "supermux.harness.nocli.docs": String(localized: "supermux.harness.nocli.docs", defaultValue: "Installation guide"),
            "supermux.harness.nocli.searchedPath": String(localized: "supermux.harness.nocli.searchedPath", defaultValue: "Searched PATH and common version-manager directories."),
            "supermux.harness.nocli.setBinary": String(localized: "supermux.harness.nocli.setBinary", defaultValue: "Point at a binary…"),
            "supermux.harness.exited.headline": String(localized: "supermux.harness.exited.headline", defaultValue: "Session ended"),
            "supermux.harness.exited.body": String(localized: "supermux.harness.exited.body", defaultValue: "The Claude process exited. Your transcript is preserved."),
            "supermux.harness.exited.restart": String(localized: "supermux.harness.exited.restart", defaultValue: "Start a new session"),
            "supermux.harness.composer.placeholder": String(localized: "supermux.harness.composer.placeholder", defaultValue: "Message Claude…"),
            "supermux.harness.composer.placeholderRunning": String(localized: "supermux.harness.composer.placeholderRunning", defaultValue: "Send a follow-up — it will be queued"),
            "supermux.harness.composer.placeholderWaiting": String(localized: "supermux.harness.composer.placeholderWaiting", defaultValue: "Respond to the request above"),
            "supermux.harness.composer.placeholderPlan": String(localized: "supermux.harness.composer.placeholderPlan", defaultValue: "Approve the plan, or say what to change"),
            "supermux.harness.composer.placeholderNoCli": String(localized: "supermux.harness.composer.placeholderNoCli", defaultValue: "Install the Claude Code CLI to start"),
            "supermux.harness.composer.placeholderRestarting": String(localized: "supermux.harness.composer.placeholderRestarting", defaultValue: "Restarting Claude…"),
            "supermux.harness.composer.send": String(localized: "supermux.harness.composer.send", defaultValue: "Send"),
            "supermux.harness.composer.stop": String(localized: "supermux.harness.composer.stop", defaultValue: "Stop"),
            "supermux.harness.composer.hintSend": String(localized: "supermux.harness.composer.hintSend", defaultValue: "Enter to send"),
            "supermux.harness.composer.hintNewline": String(localized: "supermux.harness.composer.hintNewline", defaultValue: "Shift+Enter for a new line"),
            "supermux.harness.composer.hintInterrupt": String(localized: "supermux.harness.composer.hintInterrupt", defaultValue: "Esc to interrupt"),
            "supermux.harness.composer.hintMode": String(localized: "supermux.harness.composer.hintMode", defaultValue: "Shift+Tab cycles permission mode"),
            "supermux.harness.composer.attach": String(localized: "supermux.harness.composer.attach", defaultValue: "Attach files"),
            "supermux.harness.composer.removeAttachment": String(localized: "supermux.harness.composer.removeAttachment", defaultValue: "Remove attachment"),
            "supermux.harness.composer.queued": String(localized: "supermux.harness.composer.queued", defaultValue: "Queued"),
            "supermux.harness.composer.cancelQueued": String(localized: "supermux.harness.composer.cancelQueued", defaultValue: "Cancel queued message"),
            "supermux.harness.composer.mentionTitle": String(localized: "supermux.harness.composer.mentionTitle", defaultValue: "Files"),
            "supermux.harness.composer.mentionEmpty": String(localized: "supermux.harness.composer.mentionEmpty", defaultValue: "No matching files"),
            "supermux.harness.composer.commandTitle": String(localized: "supermux.harness.composer.commandTitle", defaultValue: "Commands"),
            "supermux.harness.composer.commandEmpty": String(localized: "supermux.harness.composer.commandEmpty", defaultValue: "No matching commands"),
            "supermux.harness.composer.approxTokens": String(localized: "supermux.harness.composer.approxTokens", defaultValue: "~{count} tokens"),
            "supermux.harness.status.idle": String(localized: "supermux.harness.status.idle", defaultValue: "Ready"),
            "supermux.harness.status.thinking": String(localized: "supermux.harness.status.thinking", defaultValue: "Claude is thinking…"),
            "supermux.harness.status.thinkingTokens": String(localized: "supermux.harness.status.thinkingTokens", defaultValue: "Thinking · {tokens} tokens"),
            "supermux.harness.status.running": String(localized: "supermux.harness.status.running", defaultValue: "Running {tool}"),
            "supermux.harness.status.waitingApproval": String(localized: "supermux.harness.status.waitingApproval", defaultValue: "Waiting for your approval"),
            "supermux.harness.status.compacting": String(localized: "supermux.harness.status.compacting", defaultValue: "Compacting conversation…"),
            "supermux.harness.status.retrying": String(localized: "supermux.harness.status.retrying", defaultValue: "Retrying in {seconds}s · attempt {attempt} of {max}"),
            "supermux.harness.status.starting": String(localized: "supermux.harness.status.starting", defaultValue: "Starting Claude…"),
            "supermux.harness.status.restarting": String(localized: "supermux.harness.status.restarting", defaultValue: "Restarting Claude…"),
            "supermux.harness.status.queuedOne": String(localized: "supermux.harness.status.queuedOne", defaultValue: "{count} message queued"),
            "supermux.harness.status.queued": String(localized: "supermux.harness.status.queued", defaultValue: "{count} messages queued"),
            "supermux.harness.status.exited": String(localized: "supermux.harness.status.exited", defaultValue: "Process exited"),
            "supermux.harness.status.noCli": String(localized: "supermux.harness.status.noCli", defaultValue: "Claude Code CLI not found"),
            "supermux.harness.status.restart": String(localized: "supermux.harness.status.restart", defaultValue: "Restart"),
            "supermux.harness.status.workingFor": String(localized: "supermux.harness.status.workingFor", defaultValue: "Working for {duration}"),
            "supermux.harness.status.jumpToLatest": String(localized: "supermux.harness.status.jumpToLatest", defaultValue: "Jump to latest"),
            "supermux.harness.turn.workedFor": String(localized: "supermux.harness.turn.workedFor", defaultValue: "Worked for {duration}"),
            "supermux.harness.turn.stoppedAfter": String(localized: "supermux.harness.turn.stoppedAfter", defaultValue: "You stopped after {duration}"),
            "supermux.harness.turn.failedAfter": String(localized: "supermux.harness.turn.failedAfter", defaultValue: "Failed after {duration}"),
            "supermux.harness.turn.showFullMessage": String(localized: "supermux.harness.turn.showFullMessage", defaultValue: "Show full message"),
            "supermux.harness.turn.showLess": String(localized: "supermux.harness.turn.showLess", defaultValue: "Show less"),
            "supermux.harness.turn.interrupted": String(localized: "supermux.harness.turn.interrupted", defaultValue: "Interrupted"),
            "supermux.harness.turn.previousToolCallsOne": String(localized: "supermux.harness.turn.previousToolCallsOne", defaultValue: "{count} earlier tool call"),
            "supermux.harness.turn.previousToolCalls": String(localized: "supermux.harness.turn.previousToolCalls", defaultValue: "{count} earlier tool calls"),
            "supermux.harness.turn.earlierMessagesOne": String(localized: "supermux.harness.turn.earlierMessagesOne", defaultValue: "{count} earlier message"),
            "supermux.harness.turn.earlierMessages": String(localized: "supermux.harness.turn.earlierMessages", defaultValue: "{count} earlier messages"),
            "supermux.harness.turn.turnNumber": String(localized: "supermux.harness.turn.turnNumber", defaultValue: "Turn {seq}"),
            "supermux.harness.turn.exportTitle": String(localized: "supermux.harness.turn.exportTitle", defaultValue: "Claude session"),
            "supermux.harness.thinking.label": String(localized: "supermux.harness.thinking.label", defaultValue: "Thinking"),
            "supermux.harness.thinking.summary": String(localized: "supermux.harness.thinking.summary", defaultValue: "Thinking · {tokens} tokens · {duration}"),
            "supermux.harness.thinking.summaryNoTokens": String(localized: "supermux.harness.thinking.summaryNoTokens", defaultValue: "Thinking · {duration}"),
            "supermux.harness.thinking.redacted": String(localized: "supermux.harness.thinking.redacted", defaultValue: "Reasoning is not shown for this account."),
            "supermux.harness.tool.running": String(localized: "supermux.harness.tool.running", defaultValue: "Running"),
            "supermux.harness.tool.succeeded": String(localized: "supermux.harness.tool.succeeded", defaultValue: "Done"),
            "supermux.harness.tool.failed": String(localized: "supermux.harness.tool.failed", defaultValue: "Failed"),
            "supermux.harness.tool.denied": String(localized: "supermux.harness.tool.denied", defaultValue: "Denied"),
            "supermux.harness.tool.aborted": String(localized: "supermux.harness.tool.aborted", defaultValue: "Interrupted"),
            "supermux.harness.tool.pending": String(localized: "supermux.harness.tool.pending", defaultValue: "Preparing"),
            "supermux.harness.tool.noOutput": String(localized: "supermux.harness.tool.noOutput", defaultValue: "No output"),
            "supermux.harness.tool.showMoreOne": String(localized: "supermux.harness.tool.showMoreOne", defaultValue: "Show {count} more line"),
            "supermux.harness.tool.showMore": String(localized: "supermux.harness.tool.showMore", defaultValue: "Show {count} more lines"),
            "supermux.harness.tool.showLess": String(localized: "supermux.harness.tool.showLess", defaultValue: "Collapse output"),
            "supermux.harness.tool.copy": String(localized: "supermux.harness.tool.copy", defaultValue: "Copy"),
            "supermux.harness.tool.copied": String(localized: "supermux.harness.tool.copied", defaultValue: "Copied"),
            "supermux.harness.tool.copyFailed": String(localized: "supermux.harness.tool.copyFailed", defaultValue: "Copy failed"),
            "supermux.harness.tool.wrap": String(localized: "supermux.harness.tool.wrap", defaultValue: "Wrap lines"),
            "supermux.harness.tool.openFile": String(localized: "supermux.harness.tool.openFile", defaultValue: "Open file"),
            "supermux.harness.tool.exitCode": String(localized: "supermux.harness.tool.exitCode", defaultValue: "exit {code}"),
            "supermux.harness.tool.linesAdded": String(localized: "supermux.harness.tool.linesAdded", defaultValue: "+{count}"),
            "supermux.harness.tool.linesRemoved": String(localized: "supermux.harness.tool.linesRemoved", defaultValue: "−{count}"),
            "supermux.harness.tool.filesFoundOne": String(localized: "supermux.harness.tool.filesFoundOne", defaultValue: "{count} file"),
            "supermux.harness.tool.filesFound": String(localized: "supermux.harness.tool.filesFound", defaultValue: "{count} files"),
            "supermux.harness.tool.matchesFoundOne": String(localized: "supermux.harness.tool.matchesFoundOne", defaultValue: "{count} match"),
            "supermux.harness.tool.matchesFound": String(localized: "supermux.harness.tool.matchesFound", defaultValue: "{count} matches"),
            "supermux.harness.tool.toolsSearchedOne": String(localized: "supermux.harness.tool.toolsSearchedOne", defaultValue: "{count} tool searched"),
            "supermux.harness.tool.toolsSearched": String(localized: "supermux.harness.tool.toolsSearched", defaultValue: "{count} tools searched"),
            "supermux.harness.tool.linesReadOne": String(localized: "supermux.harness.tool.linesReadOne", defaultValue: "{count} line"),
            "supermux.harness.tool.linesRead": String(localized: "supermux.harness.tool.linesRead", defaultValue: "{count} lines"),
            "supermux.harness.tool.created": String(localized: "supermux.harness.tool.created", defaultValue: "Created"),
            "supermux.harness.tool.updated": String(localized: "supermux.harness.tool.updated", defaultValue: "Updated"),
            "supermux.harness.tool.searchResultsOne": String(localized: "supermux.harness.tool.searchResultsOne", defaultValue: "{count} result"),
            "supermux.harness.tool.searchResults": String(localized: "supermux.harness.tool.searchResults", defaultValue: "{count} results"),
            "supermux.harness.tool.mcpServer": String(localized: "supermux.harness.tool.mcpServer", defaultValue: "MCP · {server}"),
            "supermux.harness.tool.rawInput": String(localized: "supermux.harness.tool.rawInput", defaultValue: "Input"),
            "supermux.harness.tool.rawOutput": String(localized: "supermux.harness.tool.rawOutput", defaultValue: "Output"),
            "supermux.harness.tool.durationMs": String(localized: "supermux.harness.tool.durationMs", defaultValue: "{count}ms"),
            "supermux.harness.tool.webResult": String(localized: "supermux.harness.tool.webResult", defaultValue: "Result"),
            "supermux.harness.subagent.badge": String(localized: "supermux.harness.subagent.badge", defaultValue: "Subagent"),
            "supermux.harness.subagent.background": String(localized: "supermux.harness.subagent.background", defaultValue: "Background"),
            "supermux.harness.subagent.tokens": String(localized: "supermux.harness.subagent.tokens", defaultValue: "{tokens} tokens"),
            "supermux.harness.subagent.toolUsesOne": String(localized: "supermux.harness.subagent.toolUsesOne", defaultValue: "{count} tool"),
            "supermux.harness.subagent.toolUses": String(localized: "supermux.harness.subagent.toolUses", defaultValue: "{count} tools"),
            "supermux.harness.subagent.showTranscript": String(localized: "supermux.harness.subagent.showTranscript", defaultValue: "Show subagent work"),
            "supermux.harness.subagent.hideTranscript": String(localized: "supermux.harness.subagent.hideTranscript", defaultValue: "Hide subagent work"),
            "supermux.harness.subagent.openTranscript": String(localized: "supermux.harness.subagent.openTranscript", defaultValue: "Open transcript"),
            "supermux.harness.subagent.closeTranscript": String(localized: "supermux.harness.subagent.closeTranscript", defaultValue: "Close transcript"),
            "supermux.harness.subagent.transcriptLoading": String(localized: "supermux.harness.subagent.transcriptLoading", defaultValue: "Reading the agent's transcript…"),
            "supermux.harness.subagent.transcriptMissing": String(localized: "supermux.harness.subagent.transcriptMissing", defaultValue: "No transcript on disk yet — it appears once the agent writes its first message."),
            "supermux.harness.subagent.transcriptEmpty": String(localized: "supermux.harness.subagent.transcriptEmpty", defaultValue: "The agent has not recorded anything yet."),
            "supermux.harness.subagent.transcriptFailed": String(localized: "supermux.harness.subagent.transcriptFailed", defaultValue: "Could not read the agent's transcript."),
            "supermux.harness.subagent.transcriptTruncated": String(localized: "supermux.harness.subagent.transcriptTruncated", defaultValue: "Only the most recent messages are shown."),
            "supermux.harness.subagent.transcriptRefresh": String(localized: "supermux.harness.subagent.transcriptRefresh", defaultValue: "Refresh"),
            "supermux.harness.subagent.filesReadOne": String(localized: "supermux.harness.subagent.filesReadOne", defaultValue: "read {count} file"),
            "supermux.harness.subagent.filesRead": String(localized: "supermux.harness.subagent.filesRead", defaultValue: "read {count} files"),
            "supermux.harness.subagent.filesEditedOne": String(localized: "supermux.harness.subagent.filesEditedOne", defaultValue: "edited {count} file"),
            "supermux.harness.subagent.filesEdited": String(localized: "supermux.harness.subagent.filesEdited", defaultValue: "edited {count} files"),
            "supermux.harness.subagent.searchesOne": String(localized: "supermux.harness.subagent.searchesOne", defaultValue: "{count} search"),
            "supermux.harness.subagent.searches": String(localized: "supermux.harness.subagent.searches", defaultValue: "{count} searches"),
            "supermux.harness.subagent.commandsOne": String(localized: "supermux.harness.subagent.commandsOne", defaultValue: "{count} command"),
            "supermux.harness.subagent.commands": String(localized: "supermux.harness.subagent.commands", defaultValue: "{count} commands"),
            "supermux.harness.subagent.lineDelta": String(localized: "supermux.harness.subagent.lineDelta", defaultValue: "+{added} −{removed}"),
            "supermux.harness.subagent.spawnDepth": String(localized: "supermux.harness.subagent.spawnDepth", defaultValue: "Depth {depth}"),
            "supermux.harness.subagent.fromDisk": String(localized: "supermux.harness.subagent.fromDisk", defaultValue: "Agent transcript"),
            "supermux.harness.subagent.waiting": String(localized: "supermux.harness.subagent.waiting", defaultValue: "Waiting to start…"),
            "supermux.harness.subagent.nestedOne": String(localized: "supermux.harness.subagent.nestedOne", defaultValue: "{count} nested agent"),
            "supermux.harness.subagent.nested": String(localized: "supermux.harness.subagent.nested", defaultValue: "{count} nested agents"),
            "supermux.harness.workflow.badge": String(localized: "supermux.harness.workflow.badge", defaultValue: "Workflow"),
            "supermux.harness.workflow.untitled": String(localized: "supermux.harness.workflow.untitled", defaultValue: "Workflow"),
            "supermux.harness.workflow.starting": String(localized: "supermux.harness.workflow.starting", defaultValue: "Starting the workflow…"),
            "supermux.harness.workflow.phasesOne": String(localized: "supermux.harness.workflow.phasesOne", defaultValue: "{count} phase"),
            "supermux.harness.workflow.phases": String(localized: "supermux.harness.workflow.phases", defaultValue: "{count} phases"),
            "supermux.harness.workflow.agentsOne": String(localized: "supermux.harness.workflow.agentsOne", defaultValue: "{count} agent"),
            "supermux.harness.workflow.agents": String(localized: "supermux.harness.workflow.agents", defaultValue: "{count} agents"),
            "supermux.harness.workflow.phasePending": String(localized: "supermux.harness.workflow.phasePending", defaultValue: "Not started"),
            "supermux.harness.workflow.progress": String(localized: "supermux.harness.workflow.progress", defaultValue: "{done} of {total} done"),
            "supermux.harness.workflow.stop": String(localized: "supermux.harness.workflow.stop", defaultValue: "Stop workflow"),
            "supermux.harness.workflow.stopping": String(localized: "supermux.harness.workflow.stopping", defaultValue: "Stopping…"),
            "supermux.harness.workflow.stopped": String(localized: "supermux.harness.workflow.stopped", defaultValue: "Stopped"),
            "supermux.harness.workflow.stoppedAfter": String(localized: "supermux.harness.workflow.stoppedAfter", defaultValue: "Stopped after {duration}"),
            "supermux.harness.workflow.agentsFinishedOne": String(localized: "supermux.harness.workflow.agentsFinishedOne", defaultValue: "{done} of {total} agent finished"),
            "supermux.harness.workflow.agentsFinished": String(localized: "supermux.harness.workflow.agentsFinished", defaultValue: "{done} of {total} agents finished"),
            "supermux.harness.workflow.stopFailed": String(localized: "supermux.harness.workflow.stopFailed", defaultValue: "Could not stop the workflow."),
            "supermux.harness.workflow.state.queued": String(localized: "supermux.harness.workflow.state.queued", defaultValue: "Queued"),
            "supermux.harness.workflow.state.running": String(localized: "supermux.harness.workflow.state.running", defaultValue: "Running"),
            "supermux.harness.workflow.state.done": String(localized: "supermux.harness.workflow.state.done", defaultValue: "Done"),
            "supermux.harness.workflow.state.error": String(localized: "supermux.harness.workflow.state.error", defaultValue: "Failed"),
            "supermux.harness.workflow.state.blocked": String(localized: "supermux.harness.workflow.state.blocked", defaultValue: "Blocked"),
            "supermux.harness.workflow.state.cached": String(localized: "supermux.harness.workflow.state.cached", defaultValue: "Cached"),
            "supermux.harness.workflow.attempt": String(localized: "supermux.harness.workflow.attempt", defaultValue: "Attempt {count}"),
            "supermux.harness.workflow.isolationWorktree": String(localized: "supermux.harness.workflow.isolationWorktree", defaultValue: "Worktree"),
            "supermux.harness.workflow.isolationRemote": String(localized: "supermux.harness.workflow.isolationRemote", defaultValue: "Remote"),
            "supermux.harness.workflow.showResult": String(localized: "supermux.harness.workflow.showResult", defaultValue: "Show result"),
            "supermux.harness.workflow.hideResult": String(localized: "supermux.harness.workflow.hideResult", defaultValue: "Hide result"),
            "supermux.harness.workflow.showLogsOne": String(localized: "supermux.harness.workflow.showLogsOne", defaultValue: "{count} log line"),
            "supermux.harness.workflow.showLogs": String(localized: "supermux.harness.workflow.showLogs", defaultValue: "{count} log lines"),
            "supermux.harness.workflow.hideLogs": String(localized: "supermux.harness.workflow.hideLogs", defaultValue: "Hide log"),
            "supermux.harness.workflow.noAgents": String(localized: "supermux.harness.workflow.noAgents", defaultValue: "No agents have been scheduled yet."),
            "supermux.harness.workflow.unphased": String(localized: "supermux.harness.workflow.unphased", defaultValue: "Unphased"),
            "supermux.harness.workflow.openAgent": String(localized: "supermux.harness.workflow.openAgent", defaultValue: "Open agent transcript"),
            "supermux.harness.workflow.viewAgents": String(localized: "supermux.harness.workflow.viewAgents", defaultValue: "Pick an agent to open its transcript:"),
            "supermux.harness.tasks.title": String(localized: "supermux.harness.tasks.title", defaultValue: "Background tasks"),
            "supermux.harness.tasks.countOne": String(localized: "supermux.harness.tasks.countOne", defaultValue: "{count} task"),
            "supermux.harness.tasks.count": String(localized: "supermux.harness.tasks.count", defaultValue: "{count} tasks"),
            "supermux.harness.tasks.collapse": String(localized: "supermux.harness.tasks.collapse", defaultValue: "Hide background tasks"),
            "supermux.harness.tasks.expand": String(localized: "supermux.harness.tasks.expand", defaultValue: "Show background tasks"),
            "supermux.harness.tasks.typeShell": String(localized: "supermux.harness.tasks.typeShell", defaultValue: "Shell"),
            "supermux.harness.tasks.typeAgent": String(localized: "supermux.harness.tasks.typeAgent", defaultValue: "Agent"),
            "supermux.harness.tasks.typeWorkflow": String(localized: "supermux.harness.tasks.typeWorkflow", defaultValue: "Workflow"),
            "supermux.harness.tasks.typeTask": String(localized: "supermux.harness.tasks.typeTask", defaultValue: "Task"),
            "supermux.harness.tasks.statusDone": String(localized: "supermux.harness.tasks.statusDone", defaultValue: "Done"),
            "supermux.harness.tasks.statusFailed": String(localized: "supermux.harness.tasks.statusFailed", defaultValue: "Failed"),
            "supermux.harness.tasks.statusStopped": String(localized: "supermux.harness.tasks.statusStopped", defaultValue: "Stopped"),
            "supermux.harness.tasks.statusSettled": String(localized: "supermux.harness.tasks.statusSettled", defaultValue: "Settled"),
            "supermux.harness.tasks.moreBelow": String(localized: "supermux.harness.tasks.moreBelow", defaultValue: "{count} more below"),
            "supermux.harness.tasks.untitled": String(localized: "supermux.harness.tasks.untitled", defaultValue: "Background task"),
            "supermux.harness.tasks.stop": String(localized: "supermux.harness.tasks.stop", defaultValue: "Stop"),
            "supermux.harness.tasks.stopping": String(localized: "supermux.harness.tasks.stopping", defaultValue: "Stopping…"),
            "supermux.harness.tasks.stopFailed": String(localized: "supermux.harness.tasks.stopFailed", defaultValue: "Could not stop this task."),
            "supermux.harness.tasks.view": String(localized: "supermux.harness.tasks.view", defaultValue: "View"),
            "supermux.harness.tasks.hide": String(localized: "supermux.harness.tasks.hide", defaultValue: "Hide"),
            "supermux.harness.tasks.outputTitle": String(localized: "supermux.harness.tasks.outputTitle", defaultValue: "Output"),
            "supermux.harness.tasks.outputLoading": String(localized: "supermux.harness.tasks.outputLoading", defaultValue: "Reading output…"),
            "supermux.harness.tasks.outputEmpty": String(localized: "supermux.harness.tasks.outputEmpty", defaultValue: "No output yet."),
            "supermux.harness.tasks.outputMissing": String(localized: "supermux.harness.tasks.outputMissing", defaultValue: "This task has not written an output file yet."),
            "supermux.harness.tasks.outputFailed": String(localized: "supermux.harness.tasks.outputFailed", defaultValue: "Could not read the output."),
            "supermux.harness.tasks.outputTruncated": String(localized: "supermux.harness.tasks.outputTruncated", defaultValue: "Showing the end of the output."),
            "supermux.harness.tasks.outputLive": String(localized: "supermux.harness.tasks.outputLive", defaultValue: "Live"),
            "supermux.harness.bash.background": String(localized: "supermux.harness.bash.background", defaultValue: "Background"),
            "supermux.harness.bash.backgroundedByUser": String(localized: "supermux.harness.bash.backgroundedByUser", defaultValue: "Moved to background"),
            "supermux.harness.bash.autoBackgrounded": String(localized: "supermux.harness.bash.autoBackgrounded", defaultValue: "Backgrounded after {duration}"),
            "supermux.harness.bash.moveToBackground": String(localized: "supermux.harness.bash.moveToBackground", defaultValue: "Move to background"),
            "supermux.harness.bash.moveToBackgroundHint": String(localized: "supermux.harness.bash.moveToBackgroundHint", defaultValue: "Keep this command running and hand the turn back — the CLI's Ctrl+B."),
            "supermux.harness.bash.moveToBackgroundKey": String(localized: "supermux.harness.bash.moveToBackgroundKey", defaultValue: "Ctrl+B"),
            "supermux.harness.bash.moving": String(localized: "supermux.harness.bash.moving", defaultValue: "Moving…"),
            "supermux.harness.bash.moveFailed": String(localized: "supermux.harness.bash.moveFailed", defaultValue: "Could not move this command to the background."),
            "supermux.harness.bash.showOutput": String(localized: "supermux.harness.bash.showOutput", defaultValue: "Show output"),
            "supermux.harness.bash.hideOutput": String(localized: "supermux.harness.bash.hideOutput", defaultValue: "Hide output"),
            "supermux.harness.bash.stop": String(localized: "supermux.harness.bash.stop", defaultValue: "Stop"),
            "supermux.harness.bash.statusRunning": String(localized: "supermux.harness.bash.statusRunning", defaultValue: "Still running"),
            "supermux.harness.bash.statusCompleted": String(localized: "supermux.harness.bash.statusCompleted", defaultValue: "Finished"),
            "supermux.harness.bash.statusFailed": String(localized: "supermux.harness.bash.statusFailed", defaultValue: "Failed"),
            "supermux.harness.bash.statusKilled": String(localized: "supermux.harness.bash.statusKilled", defaultValue: "Stopped"),
            "supermux.harness.todo.title": String(localized: "supermux.harness.todo.title", defaultValue: "Plan"),
            "supermux.harness.todo.progress": String(localized: "supermux.harness.todo.progress", defaultValue: "{done}/{total}"),
            "supermux.harness.todo.expand": String(localized: "supermux.harness.todo.expand", defaultValue: "Show all steps"),
            "supermux.harness.todo.collapse": String(localized: "supermux.harness.todo.collapse", defaultValue: "Collapse steps"),
            "supermux.harness.permission.title": String(localized: "supermux.harness.permission.title", defaultValue: "Permission needed"),
            "supermux.harness.permission.allowOnce": String(localized: "supermux.harness.permission.allowOnce", defaultValue: "Allow once"),
            "supermux.harness.permission.allowAlways": String(localized: "supermux.harness.permission.allowAlways", defaultValue: "Always allow"),
            "supermux.harness.permission.allowAlwaysRule": String(localized: "supermux.harness.permission.allowAlwaysRule", defaultValue: "Adds rule {rule}"),
            "supermux.harness.permission.deny": String(localized: "supermux.harness.permission.deny", defaultValue: "Deny"),
            "supermux.harness.permission.denyReason": String(localized: "supermux.harness.permission.denyReason", defaultValue: "Reason (optional)"),
            "supermux.harness.permission.denyAndStop": String(localized: "supermux.harness.permission.denyAndStop", defaultValue: "Deny and stop"),
            "supermux.harness.permission.blockedPath": String(localized: "supermux.harness.permission.blockedPath", defaultValue: "Blocked path"),
            "supermux.harness.permission.moreWaiting": String(localized: "supermux.harness.permission.moreWaiting", defaultValue: "{count} more waiting"),
            "supermux.harness.permission.destinationLocal": String(localized: "supermux.harness.permission.destinationLocal", defaultValue: "this project"),
            "supermux.harness.permission.destinationProject": String(localized: "supermux.harness.permission.destinationProject", defaultValue: "the project settings"),
            "supermux.harness.permission.destinationUser": String(localized: "supermux.harness.permission.destinationUser", defaultValue: "all projects"),
            "supermux.harness.permission.destinationSession": String(localized: "supermux.harness.permission.destinationSession", defaultValue: "this session"),
            "supermux.harness.permission.denyBack": String(localized: "supermux.harness.permission.denyBack", defaultValue: "Back"),
            "supermux.harness.plan.badge": String(localized: "supermux.harness.plan.badge", defaultValue: "Plan"),
            "supermux.harness.plan.title": String(localized: "supermux.harness.plan.title", defaultValue: "Claude has a plan"),
            "supermux.harness.plan.approveAuto": String(localized: "supermux.harness.plan.approveAuto", defaultValue: "Approve & auto-accept edits"),
            "supermux.harness.plan.approveManual": String(localized: "supermux.harness.plan.approveManual", defaultValue: "Approve, ask before edits"),
            "supermux.harness.plan.keepPlanning": String(localized: "supermux.harness.plan.keepPlanning", defaultValue: "Keep planning"),
            "supermux.harness.plan.keepPlanningMessage": String(localized: "supermux.harness.plan.keepPlanningMessage", defaultValue: "Keep planning — refine the approach first."),
            "supermux.harness.plan.copy": String(localized: "supermux.harness.plan.copy", defaultValue: "Copy plan"),
            "supermux.harness.plan.download": String(localized: "supermux.harness.plan.download", defaultValue: "Download plan as Markdown"),
            "supermux.harness.plan.implement": String(localized: "supermux.harness.plan.implement", defaultValue: "Implement"),
            "supermux.harness.plan.refine": String(localized: "supermux.harness.plan.refine", defaultValue: "Refine"),
            "supermux.harness.question.badge": String(localized: "supermux.harness.question.badge", defaultValue: "Question"),
            "supermux.harness.question.title": String(localized: "supermux.harness.question.title", defaultValue: "Claude has a question"),
            "supermux.harness.question.other": String(localized: "supermux.harness.question.other", defaultValue: "Something else"),
            "supermux.harness.question.otherPlaceholder": String(localized: "supermux.harness.question.otherPlaceholder", defaultValue: "Type your answer…"),
            "supermux.harness.question.submit": String(localized: "supermux.harness.question.submit", defaultValue: "Submit"),
            "supermux.harness.question.selectMultiple": String(localized: "supermux.harness.question.selectMultiple", defaultValue: "Select all that apply"),
            "supermux.harness.question.dismiss": String(localized: "supermux.harness.question.dismiss", defaultValue: "Skip"),
            "supermux.harness.question.dismissed": String(localized: "supermux.harness.question.dismissed", defaultValue: "Dismissed"),
            "supermux.harness.question.unanswered": String(localized: "supermux.harness.question.unanswered", defaultValue: "Not answered yet"),
            "supermux.harness.question.willSend": String(localized: "supermux.harness.question.willSend", defaultValue: "Will send: {answer}"),
            "supermux.harness.header.rename": String(localized: "supermux.harness.header.rename", defaultValue: "Rename session"),
            "supermux.harness.header.renameSave": String(localized: "supermux.harness.header.renameSave", defaultValue: "Save"),
            "supermux.harness.header.renameCancel": String(localized: "supermux.harness.header.renameCancel", defaultValue: "Cancel"),
            "supermux.harness.header.model": String(localized: "supermux.harness.header.model", defaultValue: "Model"),
            "supermux.harness.header.effort": String(localized: "supermux.harness.header.effort", defaultValue: "Effort"),
            "supermux.harness.header.effortDefault": String(localized: "supermux.harness.header.effortDefault", defaultValue: "Default"),
            "supermux.harness.effort.low": String(localized: "supermux.harness.effort.low", defaultValue: "Low"),
            "supermux.harness.effort.medium": String(localized: "supermux.harness.effort.medium", defaultValue: "Medium"),
            "supermux.harness.effort.high": String(localized: "supermux.harness.effort.high", defaultValue: "High"),
            "supermux.harness.effort.xhigh": String(localized: "supermux.harness.effort.xhigh", defaultValue: "Extra high"),
            "supermux.harness.effort.max": String(localized: "supermux.harness.effort.max", defaultValue: "Max"),
            "supermux.harness.header.permissionMode": String(localized: "supermux.harness.header.permissionMode", defaultValue: "Permissions"),
            "supermux.harness.header.context": String(localized: "supermux.harness.header.context", defaultValue: "Context"),
            "supermux.harness.header.contextUsed": String(localized: "supermux.harness.header.contextUsed", defaultValue: "{used} of {total} used"),
            "supermux.harness.header.contextAutoCompact": String(localized: "supermux.harness.header.contextAutoCompact", defaultValue: "Auto-compacts at {threshold}"),
            "supermux.harness.header.cost": String(localized: "supermux.harness.header.cost", defaultValue: "Cost"),
            "supermux.harness.header.sessions": String(localized: "supermux.harness.header.sessions", defaultValue: "Sessions"),
            "supermux.harness.header.sessionsSearch": String(localized: "supermux.harness.header.sessionsSearch", defaultValue: "Search sessions"),
            "supermux.harness.header.sessionsEmpty": String(localized: "supermux.harness.header.sessionsEmpty", defaultValue: "No sessions yet for this folder"),
            "supermux.harness.header.resume": String(localized: "supermux.harness.header.resume", defaultValue: "Resume"),
            "supermux.harness.header.resumeHint": String(localized: "supermux.harness.header.resumeHint", defaultValue: "Replaces this pane's session"),
            "supermux.harness.header.fork": String(localized: "supermux.harness.header.fork", defaultValue: "Fork"),
            "supermux.harness.header.forkHint": String(localized: "supermux.harness.header.forkHint", defaultValue: "Branch into a copy, leaving this one untouched"),
            "supermux.harness.header.openInNewPane": String(localized: "supermux.harness.header.openInNewPane", defaultValue: "New pane"),
            "supermux.harness.header.openInNewPaneHint": String(localized: "supermux.harness.header.openInNewPaneHint", defaultValue: "Open beside this one, both live at once"),
            "supermux.harness.header.more": String(localized: "supermux.harness.header.more", defaultValue: "More"),
            "supermux.harness.header.compact": String(localized: "supermux.harness.header.compact", defaultValue: "Compact conversation"),
            "supermux.harness.header.clear": String(localized: "supermux.harness.header.clear", defaultValue: "Clear conversation"),
            "supermux.harness.header.export": String(localized: "supermux.harness.header.export", defaultValue: "Export transcript"),
            "supermux.harness.header.openTerminal": String(localized: "supermux.harness.header.openTerminal", defaultValue: "Open folder in terminal"),
            "supermux.harness.header.newSession": String(localized: "supermux.harness.header.newSession", defaultValue: "New session"),
            "supermux.harness.header.binary": String(localized: "supermux.harness.header.binary", defaultValue: "Claude binary…"),
            "supermux.harness.header.modelsLoading": String(localized: "supermux.harness.header.modelsLoading", defaultValue: "Loading models…"),
            "supermux.harness.binary.title": String(localized: "supermux.harness.binary.title", defaultValue: "Claude binary"),
            "supermux.harness.binary.resolved": String(localized: "supermux.harness.binary.resolved", defaultValue: "Currently using"),
            "supermux.harness.binary.resolvedNone": String(localized: "supermux.harness.binary.resolvedNone", defaultValue: "No binary resolved"),
            "supermux.harness.binary.overrideLabel": String(localized: "supermux.harness.binary.overrideLabel", defaultValue: "Custom path"),
            "supermux.harness.binary.overridePlaceholder": String(localized: "supermux.harness.binary.overridePlaceholder", defaultValue: "/Users/you/.local/bin/ccx"),
            "supermux.harness.binary.help": String(localized: "supermux.harness.binary.help", defaultValue: "Point the pane at your own launcher or wrapper script. Leave it empty to search PATH."),
            "supermux.harness.binary.appliesNextStart": String(localized: "supermux.harness.binary.appliesNextStart", defaultValue: "Applies the next time the session starts."),
            "supermux.harness.binary.save": String(localized: "supermux.harness.binary.save", defaultValue: "Save"),
            "supermux.harness.binary.clear": String(localized: "supermux.harness.binary.clear", defaultValue: "Clear"),
            "supermux.harness.binary.cancel": String(localized: "supermux.harness.binary.cancel", defaultValue: "Cancel"),
            "supermux.harness.binary.saved": String(localized: "supermux.harness.binary.saved", defaultValue: "Saved"),
            "supermux.harness.binary.version": String(localized: "supermux.harness.binary.version", defaultValue: "Version {version}"),
            "supermux.harness.rewind.action": String(localized: "supermux.harness.rewind.action", defaultValue: "Rewind"),
            "supermux.harness.rewind.title": String(localized: "supermux.harness.rewind.title", defaultValue: "Rewind to this message"),
            "supermux.harness.rewind.body": String(localized: "supermux.harness.rewind.body", defaultValue: "Everything after this message is dropped, and its text goes back in the composer to edit."),
            "supermux.harness.rewind.restoreFiles": String(localized: "supermux.harness.rewind.restoreFiles", defaultValue: "Also restore files to this point"),
            "supermux.harness.rewind.checking": String(localized: "supermux.harness.rewind.checking", defaultValue: "Checking what changed…"),
            "supermux.harness.rewind.filesChangedOne": String(localized: "supermux.harness.rewind.filesChangedOne", defaultValue: "{count} file · +{added} −{removed}"),
            "supermux.harness.rewind.filesChanged": String(localized: "supermux.harness.rewind.filesChanged", defaultValue: "{count} files · +{added} −{removed}"),
            "supermux.harness.rewind.noFiles": String(localized: "supermux.harness.rewind.noFiles", defaultValue: "No file changes to restore"),
            "supermux.harness.rewind.unavailable": String(localized: "supermux.harness.rewind.unavailable", defaultValue: "This session has no file checkpoints, so only the conversation can be rewound."),
            "supermux.harness.rewind.confirm": String(localized: "supermux.harness.rewind.confirm", defaultValue: "Rewind & edit"),
            "supermux.harness.rewind.cancel": String(localized: "supermux.harness.rewind.cancel", defaultValue: "Cancel"),
            "supermux.harness.rewind.done": String(localized: "supermux.harness.rewind.done", defaultValue: "Rewound to before this message."),
            "supermux.harness.rewind.doneFilesFailed": String(localized: "supermux.harness.rewind.doneFilesFailed", defaultValue: "Conversation rewound; files could not be restored."),
            "supermux.harness.rewind.failed": String(localized: "supermux.harness.rewind.failed", defaultValue: "Rewind failed"),
            "supermux.harness.mode.default": String(localized: "supermux.harness.mode.default", defaultValue: "Ask each time"),
            "supermux.harness.mode.defaultShort": String(localized: "supermux.harness.mode.defaultShort", defaultValue: "Ask"),
            "supermux.harness.mode.acceptEdits": String(localized: "supermux.harness.mode.acceptEdits", defaultValue: "Auto-accept edits"),
            "supermux.harness.mode.acceptEditsShort": String(localized: "supermux.harness.mode.acceptEditsShort", defaultValue: "Auto-edit"),
            "supermux.harness.mode.plan": String(localized: "supermux.harness.mode.plan", defaultValue: "Plan only"),
            "supermux.harness.mode.planShort": String(localized: "supermux.harness.mode.planShort", defaultValue: "Plan"),
            "supermux.harness.mode.bypassPermissions": String(localized: "supermux.harness.mode.bypassPermissions", defaultValue: "Bypass all prompts"),
            "supermux.harness.mode.bypassPermissionsShort": String(localized: "supermux.harness.mode.bypassPermissionsShort", defaultValue: "Bypass"),
            "supermux.harness.divider.compact": String(localized: "supermux.harness.divider.compact", defaultValue: "Conversation compacted"),
            "supermux.harness.divider.compactTokens": String(localized: "supermux.harness.divider.compactTokens", defaultValue: "{tokens} tokens summarized"),
            "supermux.harness.divider.reset": String(localized: "supermux.harness.divider.reset", defaultValue: "Conversation cleared"),
            "supermux.harness.history.truncated": String(localized: "supermux.harness.history.truncated", defaultValue: "Earlier messages in this session are not shown"),
            "supermux.harness.notice.taskFinished": String(localized: "supermux.harness.notice.taskFinished", defaultValue: "Background task finished — {subject}"),
            "supermux.harness.notice.taskStopped": String(localized: "supermux.harness.notice.taskStopped", defaultValue: "Background task stopped — {subject}"),
            "supermux.harness.notice.taskFailed": String(localized: "supermux.harness.notice.taskFailed", defaultValue: "Background task failed — {subject}"),
            "supermux.harness.notice.workflowFinished": String(localized: "supermux.harness.notice.workflowFinished", defaultValue: "Workflow finished — {subject}"),
            "supermux.harness.notice.workflowStopped": String(localized: "supermux.harness.notice.workflowStopped", defaultValue: "Workflow stopped — {subject}"),
            "supermux.harness.notice.workflowFailed": String(localized: "supermux.harness.notice.workflowFailed", defaultValue: "Workflow failed — {subject}"),
            "supermux.harness.banner.dismiss": String(localized: "supermux.harness.banner.dismiss", defaultValue: "Dismiss"),
            "supermux.harness.banner.retryAttempt": String(localized: "supermux.harness.banner.retryAttempt", defaultValue: "Attempt {attempt} of {max}"),
            "supermux.harness.error.generic": String(localized: "supermux.harness.error.generic", defaultValue: "Something went wrong"),
            "supermux.harness.error.rateLimit": String(localized: "supermux.harness.error.rateLimit", defaultValue: "Usage limit reached"),
            "supermux.harness.error.billing": String(localized: "supermux.harness.error.billing", defaultValue: "Billing problem"),
            "supermux.harness.error.auth": String(localized: "supermux.harness.error.auth", defaultValue: "Authentication failed"),
            "supermux.harness.error.startFailed": String(localized: "supermux.harness.error.startFailed", defaultValue: "Could not start Claude"),
            "supermux.harness.a11y.transcript": String(localized: "supermux.harness.a11y.transcript", defaultValue: "Conversation transcript"),
            "supermux.harness.a11y.composer": String(localized: "supermux.harness.a11y.composer", defaultValue: "Message composer"),
            "supermux.harness.a11y.permissionAlert": String(localized: "supermux.harness.a11y.permissionAlert", defaultValue: "Claude needs permission to continue"),
            "supermux.harness.a11y.timeline": String(localized: "supermux.harness.a11y.timeline", defaultValue: "Conversation timeline"),
            "supermux.harness.a11y.closeDialog": String(localized: "supermux.harness.a11y.closeDialog", defaultValue: "Close"),
            "supermux.harness.time.seconds": String(localized: "supermux.harness.time.seconds", defaultValue: "{value}s"),
            "supermux.harness.time.minutes": String(localized: "supermux.harness.time.minutes", defaultValue: "{value}m {seconds}s"),
            "supermux.harness.time.hours": String(localized: "supermux.harness.time.hours", defaultValue: "{value}h {minutes}m"),
            "supermux.harness.time.justNow": String(localized: "supermux.harness.time.justNow", defaultValue: "just now"),
            "supermux.harness.time.minutesAgo": String(localized: "supermux.harness.time.minutesAgo", defaultValue: "{value}m ago"),
            "supermux.harness.time.hoursAgo": String(localized: "supermux.harness.time.hoursAgo", defaultValue: "{value}h ago"),
            "supermux.harness.time.daysAgo": String(localized: "supermux.harness.time.daysAgo", defaultValue: "{value}d ago"),
        ]
    }
}
