import Foundation

/// English copy for the harness web UI; every key mirrors harness-web/src/copyKeys.ts.
enum SupermuxHarnessCopy {
    static func dictionary() -> [String: String] {
        [
            "supermux.harness.app.title": String(localized: "supermux.harness.app.title", defaultValue: "Claude"),
            "supermux.harness.app.untitledSession": String(localized: "supermux.harness.app.untitledSession", defaultValue: "New session"),
            "supermux.harness.empty.headline": String(localized: "supermux.harness.empty.headline", defaultValue: "Claude Code, in your workspace"),
            "supermux.harness.empty.subhead": String(localized: "supermux.harness.empty.subhead", defaultValue: "Ask a question, describe a change, or paste an error."),
            "supermux.harness.empty.workingIn": String(localized: "supermux.harness.empty.workingIn", defaultValue: "Working in"),
            "supermux.harness.empty.recentSessions": String(localized: "supermux.harness.empty.recentSessions", defaultValue: "Recent sessions"),
            "supermux.harness.empty.suggestionsTitle": String(localized: "supermux.harness.empty.suggestionsTitle", defaultValue: "Try one of these"),
            "supermux.harness.empty.suggestion1": String(localized: "supermux.harness.empty.suggestion1", defaultValue: "Explain how this project is structured"),
            "supermux.harness.empty.suggestion2": String(localized: "supermux.harness.empty.suggestion2", defaultValue: "Find and fix the failing test"),
            "supermux.harness.empty.suggestion3": String(localized: "supermux.harness.empty.suggestion3", defaultValue: "Review my uncommitted changes"),
            "supermux.harness.empty.detectingModel": String(localized: "supermux.harness.empty.detectingModel", defaultValue: "Detecting model…"),
            "supermux.harness.nocli.headline": String(localized: "supermux.harness.nocli.headline", defaultValue: "Claude Code CLI not found"),
            "supermux.harness.nocli.body": String(localized: "supermux.harness.nocli.body", defaultValue: "This pane drives the Claude Code command-line tool. Install it, then retry."),
            "supermux.harness.nocli.install": String(localized: "supermux.harness.nocli.install", defaultValue: "npm install -g @anthropic-ai/claude-code"),
            "supermux.harness.nocli.retry": String(localized: "supermux.harness.nocli.retry", defaultValue: "Retry detection"),
            "supermux.harness.nocli.docs": String(localized: "supermux.harness.nocli.docs", defaultValue: "Installation guide"),
            "supermux.harness.nocli.searchedPath": String(localized: "supermux.harness.nocli.searchedPath", defaultValue: "Searched PATH and common version-manager directories."),
            "supermux.harness.exited.headline": String(localized: "supermux.harness.exited.headline", defaultValue: "Session ended"),
            "supermux.harness.exited.body": String(localized: "supermux.harness.exited.body", defaultValue: "The Claude process exited. Your transcript is preserved."),
            "supermux.harness.exited.restart": String(localized: "supermux.harness.exited.restart", defaultValue: "Start a new session"),
            "supermux.harness.composer.placeholder": String(localized: "supermux.harness.composer.placeholder", defaultValue: "Message Claude…"),
            "supermux.harness.composer.placeholderRunning": String(localized: "supermux.harness.composer.placeholderRunning", defaultValue: "Send a follow-up — it will be queued"),
            "supermux.harness.composer.placeholderWaiting": String(localized: "supermux.harness.composer.placeholderWaiting", defaultValue: "Respond to the request above"),
            "supermux.harness.composer.placeholderPlan": String(localized: "supermux.harness.composer.placeholderPlan", defaultValue: "Approve the plan, or say what to change"),
            "supermux.harness.composer.placeholderNoCli": String(localized: "supermux.harness.composer.placeholderNoCli", defaultValue: "Install the Claude Code CLI to start"),
            "supermux.harness.composer.send": String(localized: "supermux.harness.composer.send", defaultValue: "Send"),
            "supermux.harness.composer.stop": String(localized: "supermux.harness.composer.stop", defaultValue: "Stop"),
            "supermux.harness.composer.hintSend": String(localized: "supermux.harness.composer.hintSend", defaultValue: "Enter to send"),
            "supermux.harness.composer.hintNewline": String(localized: "supermux.harness.composer.hintNewline", defaultValue: "Shift+Enter for a new line"),
            "supermux.harness.composer.hintInterrupt": String(localized: "supermux.harness.composer.hintInterrupt", defaultValue: "Esc to interrupt"),
            "supermux.harness.composer.hintMode": String(localized: "supermux.harness.composer.hintMode", defaultValue: "Shift+Tab cycles permission mode"),
            "supermux.harness.composer.attach": String(localized: "supermux.harness.composer.attach", defaultValue: "Attach files"),
            "supermux.harness.composer.removeAttachment": String(localized: "supermux.harness.composer.removeAttachment", defaultValue: "Remove attachment"),
            "supermux.harness.composer.queued": String(localized: "supermux.harness.composer.queued", defaultValue: "Queued"),
            "supermux.harness.composer.cancelQueued": String(localized: "supermux.harness.composer.cancelQueued", defaultValue: "Cancel queued message"),
            "supermux.harness.composer.mentionTitle": String(localized: "supermux.harness.composer.mentionTitle", defaultValue: "Files"),
            "supermux.harness.composer.mentionEmpty": String(localized: "supermux.harness.composer.mentionEmpty", defaultValue: "No matching files"),
            "supermux.harness.composer.commandTitle": String(localized: "supermux.harness.composer.commandTitle", defaultValue: "Commands"),
            "supermux.harness.composer.commandEmpty": String(localized: "supermux.harness.composer.commandEmpty", defaultValue: "No matching commands"),
            "supermux.harness.composer.approxTokens": String(localized: "supermux.harness.composer.approxTokens", defaultValue: "~{count} tokens"),
            "supermux.harness.status.idle": String(localized: "supermux.harness.status.idle", defaultValue: "Ready"),
            "supermux.harness.status.thinking": String(localized: "supermux.harness.status.thinking", defaultValue: "Claude is thinking…"),
            "supermux.harness.status.thinkingTokens": String(localized: "supermux.harness.status.thinkingTokens", defaultValue: "Thinking · {tokens} tokens"),
            "supermux.harness.status.running": String(localized: "supermux.harness.status.running", defaultValue: "Running {tool}"),
            "supermux.harness.status.waitingApproval": String(localized: "supermux.harness.status.waitingApproval", defaultValue: "Waiting for your approval"),
            "supermux.harness.status.compacting": String(localized: "supermux.harness.status.compacting", defaultValue: "Compacting conversation…"),
            "supermux.harness.status.retrying": String(localized: "supermux.harness.status.retrying", defaultValue: "Retrying in {seconds}s · attempt {attempt} of {max}"),
            "supermux.harness.status.starting": String(localized: "supermux.harness.status.starting", defaultValue: "Starting Claude…"),
            "supermux.harness.status.exited": String(localized: "supermux.harness.status.exited", defaultValue: "Process exited"),
            "supermux.harness.status.noCli": String(localized: "supermux.harness.status.noCli", defaultValue: "Claude Code CLI not found"),
            "supermux.harness.status.restart": String(localized: "supermux.harness.status.restart", defaultValue: "Restart"),
            "supermux.harness.status.workingFor": String(localized: "supermux.harness.status.workingFor", defaultValue: "Working for {duration}"),
            "supermux.harness.status.jumpToLatest": String(localized: "supermux.harness.status.jumpToLatest", defaultValue: "Jump to latest"),
            "supermux.harness.turn.workedFor": String(localized: "supermux.harness.turn.workedFor", defaultValue: "Worked for {duration}"),
            "supermux.harness.turn.stoppedAfter": String(localized: "supermux.harness.turn.stoppedAfter", defaultValue: "You stopped after {duration}"),
            "supermux.harness.turn.failedAfter": String(localized: "supermux.harness.turn.failedAfter", defaultValue: "Failed after {duration}"),
            "supermux.harness.turn.showFullMessage": String(localized: "supermux.harness.turn.showFullMessage", defaultValue: "Show full message"),
            "supermux.harness.turn.showLess": String(localized: "supermux.harness.turn.showLess", defaultValue: "Show less"),
            "supermux.harness.turn.interrupted": String(localized: "supermux.harness.turn.interrupted", defaultValue: "Interrupted"),
            "supermux.harness.turn.previousToolCallsOne": String(localized: "supermux.harness.turn.previousToolCallsOne", defaultValue: "{count} earlier tool call"),
            "supermux.harness.turn.previousToolCalls": String(localized: "supermux.harness.turn.previousToolCalls", defaultValue: "{count} earlier tool calls"),
            "supermux.harness.turn.earlierMessagesOne": String(localized: "supermux.harness.turn.earlierMessagesOne", defaultValue: "{count} earlier message"),
            "supermux.harness.turn.earlierMessages": String(localized: "supermux.harness.turn.earlierMessages", defaultValue: "{count} earlier messages"),
            "supermux.harness.turn.turnNumber": String(localized: "supermux.harness.turn.turnNumber", defaultValue: "Turn {seq}"),
            "supermux.harness.turn.complete": String(localized: "supermux.harness.turn.complete", defaultValue: "Turn complete"),
            "supermux.harness.turn.exportTitle": String(localized: "supermux.harness.turn.exportTitle", defaultValue: "Claude session"),
            "supermux.harness.thinking.label": String(localized: "supermux.harness.thinking.label", defaultValue: "Thinking"),
            "supermux.harness.thinking.summary": String(localized: "supermux.harness.thinking.summary", defaultValue: "Thinking · {tokens} tokens · {duration}"),
            "supermux.harness.thinking.summaryNoTokens": String(localized: "supermux.harness.thinking.summaryNoTokens", defaultValue: "Thinking · {duration}"),
            "supermux.harness.thinking.redacted": String(localized: "supermux.harness.thinking.redacted", defaultValue: "Reasoning is not shown for this account."),
            "supermux.harness.tool.running": String(localized: "supermux.harness.tool.running", defaultValue: "Running"),
            "supermux.harness.tool.succeeded": String(localized: "supermux.harness.tool.succeeded", defaultValue: "Done"),
            "supermux.harness.tool.failed": String(localized: "supermux.harness.tool.failed", defaultValue: "Failed"),
            "supermux.harness.tool.denied": String(localized: "supermux.harness.tool.denied", defaultValue: "Denied"),
            "supermux.harness.tool.aborted": String(localized: "supermux.harness.tool.aborted", defaultValue: "Interrupted"),
            "supermux.harness.tool.pending": String(localized: "supermux.harness.tool.pending", defaultValue: "Preparing"),
            "supermux.harness.tool.noOutput": String(localized: "supermux.harness.tool.noOutput", defaultValue: "No output"),
            "supermux.harness.tool.showMoreOne": String(localized: "supermux.harness.tool.showMoreOne", defaultValue: "Show {count} more line"),
            "supermux.harness.tool.showMore": String(localized: "supermux.harness.tool.showMore", defaultValue: "Show {count} more lines"),
            "supermux.harness.tool.showLess": String(localized: "supermux.harness.tool.showLess", defaultValue: "Collapse output"),
            "supermux.harness.tool.copy": String(localized: "supermux.harness.tool.copy", defaultValue: "Copy"),
            "supermux.harness.tool.copied": String(localized: "supermux.harness.tool.copied", defaultValue: "Copied"),
            "supermux.harness.tool.copyFailed": String(localized: "supermux.harness.tool.copyFailed", defaultValue: "Copy failed"),
            "supermux.harness.tool.wrap": String(localized: "supermux.harness.tool.wrap", defaultValue: "Wrap lines"),
            "supermux.harness.tool.openFile": String(localized: "supermux.harness.tool.openFile", defaultValue: "Open file"),
            "supermux.harness.tool.exitCode": String(localized: "supermux.harness.tool.exitCode", defaultValue: "exit {code}"),
            "supermux.harness.tool.linesAdded": String(localized: "supermux.harness.tool.linesAdded", defaultValue: "+{count}"),
            "supermux.harness.tool.linesRemoved": String(localized: "supermux.harness.tool.linesRemoved", defaultValue: "−{count}"),
            "supermux.harness.tool.filesFoundOne": String(localized: "supermux.harness.tool.filesFoundOne", defaultValue: "{count} file"),
            "supermux.harness.tool.filesFound": String(localized: "supermux.harness.tool.filesFound", defaultValue: "{count} files"),
            "supermux.harness.tool.matchesFoundOne": String(localized: "supermux.harness.tool.matchesFoundOne", defaultValue: "{count} match"),
            "supermux.harness.tool.matchesFound": String(localized: "supermux.harness.tool.matchesFound", defaultValue: "{count} matches"),
            "supermux.harness.tool.toolsSearchedOne": String(localized: "supermux.harness.tool.toolsSearchedOne", defaultValue: "{count} tool searched"),
            "supermux.harness.tool.toolsSearched": String(localized: "supermux.harness.tool.toolsSearched", defaultValue: "{count} tools searched"),
            "supermux.harness.tool.linesReadOne": String(localized: "supermux.harness.tool.linesReadOne", defaultValue: "{count} line"),
            "supermux.harness.tool.linesRead": String(localized: "supermux.harness.tool.linesRead", defaultValue: "{count} lines"),
            "supermux.harness.tool.created": String(localized: "supermux.harness.tool.created", defaultValue: "Created"),
            "supermux.harness.tool.updated": String(localized: "supermux.harness.tool.updated", defaultValue: "Updated"),
            "supermux.harness.tool.searchResultsOne": String(localized: "supermux.harness.tool.searchResultsOne", defaultValue: "{count} result"),
            "supermux.harness.tool.searchResults": String(localized: "supermux.harness.tool.searchResults", defaultValue: "{count} results"),
            "supermux.harness.tool.mcpServer": String(localized: "supermux.harness.tool.mcpServer", defaultValue: "MCP · {server}"),
            "supermux.harness.tool.rawInput": String(localized: "supermux.harness.tool.rawInput", defaultValue: "Input"),
            "supermux.harness.tool.rawOutput": String(localized: "supermux.harness.tool.rawOutput", defaultValue: "Output"),
            "supermux.harness.tool.durationMs": String(localized: "supermux.harness.tool.durationMs", defaultValue: "{count}ms"),
            "supermux.harness.tool.webResult": String(localized: "supermux.harness.tool.webResult", defaultValue: "Result"),
            "supermux.harness.subagent.badge": String(localized: "supermux.harness.subagent.badge", defaultValue: "Subagent"),
            "supermux.harness.subagent.background": String(localized: "supermux.harness.subagent.background", defaultValue: "Background"),
            "supermux.harness.subagent.tokens": String(localized: "supermux.harness.subagent.tokens", defaultValue: "{tokens} tokens"),
            "supermux.harness.subagent.toolUsesOne": String(localized: "supermux.harness.subagent.toolUsesOne", defaultValue: "{count} tool"),
            "supermux.harness.subagent.toolUses": String(localized: "supermux.harness.subagent.toolUses", defaultValue: "{count} tools"),
            "supermux.harness.subagent.showTranscript": String(localized: "supermux.harness.subagent.showTranscript", defaultValue: "Show subagent work"),
            "supermux.harness.subagent.hideTranscript": String(localized: "supermux.harness.subagent.hideTranscript", defaultValue: "Hide subagent work"),
            "supermux.harness.todo.title": String(localized: "supermux.harness.todo.title", defaultValue: "Plan"),
            "supermux.harness.todo.progress": String(localized: "supermux.harness.todo.progress", defaultValue: "{done}/{total}"),
            "supermux.harness.todo.expand": String(localized: "supermux.harness.todo.expand", defaultValue: "Show all steps"),
            "supermux.harness.todo.collapse": String(localized: "supermux.harness.todo.collapse", defaultValue: "Collapse steps"),
            "supermux.harness.permission.title": String(localized: "supermux.harness.permission.title", defaultValue: "Permission needed"),
            "supermux.harness.permission.allowOnce": String(localized: "supermux.harness.permission.allowOnce", defaultValue: "Allow once"),
            "supermux.harness.permission.allowAlways": String(localized: "supermux.harness.permission.allowAlways", defaultValue: "Always allow"),
            "supermux.harness.permission.allowAlwaysRule": String(localized: "supermux.harness.permission.allowAlwaysRule", defaultValue: "Adds rule {rule}"),
            "supermux.harness.permission.deny": String(localized: "supermux.harness.permission.deny", defaultValue: "Deny"),
            "supermux.harness.permission.denyReason": String(localized: "supermux.harness.permission.denyReason", defaultValue: "Reason (optional)"),
            "supermux.harness.permission.denyAndStop": String(localized: "supermux.harness.permission.denyAndStop", defaultValue: "Deny and stop"),
            "supermux.harness.permission.blockedPath": String(localized: "supermux.harness.permission.blockedPath", defaultValue: "Blocked path"),
            "supermux.harness.permission.moreWaiting": String(localized: "supermux.harness.permission.moreWaiting", defaultValue: "{count} more waiting"),
            "supermux.harness.permission.destinationLocal": String(localized: "supermux.harness.permission.destinationLocal", defaultValue: "this project"),
            "supermux.harness.permission.destinationProject": String(localized: "supermux.harness.permission.destinationProject", defaultValue: "the project settings"),
            "supermux.harness.permission.destinationUser": String(localized: "supermux.harness.permission.destinationUser", defaultValue: "all projects"),
            "supermux.harness.permission.destinationSession": String(localized: "supermux.harness.permission.destinationSession", defaultValue: "this session"),
            "supermux.harness.permission.denyBack": String(localized: "supermux.harness.permission.denyBack", defaultValue: "Back"),
            "supermux.harness.permission.needed": String(localized: "supermux.harness.permission.needed", defaultValue: "Permission needed"),
            "supermux.harness.plan.badge": String(localized: "supermux.harness.plan.badge", defaultValue: "Plan"),
            "supermux.harness.plan.title": String(localized: "supermux.harness.plan.title", defaultValue: "Claude has a plan"),
            "supermux.harness.plan.approveAuto": String(localized: "supermux.harness.plan.approveAuto", defaultValue: "Approve & auto-accept edits"),
            "supermux.harness.plan.approveManual": String(localized: "supermux.harness.plan.approveManual", defaultValue: "Approve, ask before edits"),
            "supermux.harness.plan.keepPlanning": String(localized: "supermux.harness.plan.keepPlanning", defaultValue: "Keep planning"),
            "supermux.harness.plan.keepPlanningMessage": String(localized: "supermux.harness.plan.keepPlanningMessage", defaultValue: "Keep planning — refine the approach first."),
            "supermux.harness.plan.copy": String(localized: "supermux.harness.plan.copy", defaultValue: "Copy plan"),
            "supermux.harness.plan.download": String(localized: "supermux.harness.plan.download", defaultValue: "Download plan as Markdown"),
            "supermux.harness.plan.implement": String(localized: "supermux.harness.plan.implement", defaultValue: "Implement"),
            "supermux.harness.plan.refine": String(localized: "supermux.harness.plan.refine", defaultValue: "Refine"),
            "supermux.harness.question.badge": String(localized: "supermux.harness.question.badge", defaultValue: "Question"),
            "supermux.harness.question.title": String(localized: "supermux.harness.question.title", defaultValue: "Claude has a question"),
            "supermux.harness.question.other": String(localized: "supermux.harness.question.other", defaultValue: "Something else"),
            "supermux.harness.question.otherPlaceholder": String(localized: "supermux.harness.question.otherPlaceholder", defaultValue: "Type your answer…"),
            "supermux.harness.question.submit": String(localized: "supermux.harness.question.submit", defaultValue: "Submit"),
            "supermux.harness.question.selectMultiple": String(localized: "supermux.harness.question.selectMultiple", defaultValue: "Select all that apply"),
            "supermux.harness.question.dismiss": String(localized: "supermux.harness.question.dismiss", defaultValue: "Skip"),
            "supermux.harness.question.dismissed": String(localized: "supermux.harness.question.dismissed", defaultValue: "Dismissed"),
            "supermux.harness.question.unanswered": String(localized: "supermux.harness.question.unanswered", defaultValue: "Not answered yet"),
            "supermux.harness.question.willSend": String(localized: "supermux.harness.question.willSend", defaultValue: "Will send: {answer}"),
            "supermux.harness.header.rename": String(localized: "supermux.harness.header.rename", defaultValue: "Rename session"),
            "supermux.harness.header.renameSave": String(localized: "supermux.harness.header.renameSave", defaultValue: "Save"),
            "supermux.harness.header.renameCancel": String(localized: "supermux.harness.header.renameCancel", defaultValue: "Cancel"),
            "supermux.harness.header.model": String(localized: "supermux.harness.header.model", defaultValue: "Model"),
            "supermux.harness.header.effort": String(localized: "supermux.harness.header.effort", defaultValue: "Effort"),
            "supermux.harness.header.effortDefault": String(localized: "supermux.harness.header.effortDefault", defaultValue: "Default"),
            "supermux.harness.header.permissionMode": String(localized: "supermux.harness.header.permissionMode", defaultValue: "Permissions"),
            "supermux.harness.header.context": String(localized: "supermux.harness.header.context", defaultValue: "Context"),
            "supermux.harness.header.contextUsed": String(localized: "supermux.harness.header.contextUsed", defaultValue: "{used} of {total} used"),
            "supermux.harness.header.contextAutoCompact": String(localized: "supermux.harness.header.contextAutoCompact", defaultValue: "Auto-compacts at {threshold}"),
            "supermux.harness.header.cost": String(localized: "supermux.harness.header.cost", defaultValue: "Cost"),
            "supermux.harness.header.sessions": String(localized: "supermux.harness.header.sessions", defaultValue: "Sessions"),
            "supermux.harness.header.sessionsSearch": String(localized: "supermux.harness.header.sessionsSearch", defaultValue: "Search sessions"),
            "supermux.harness.header.sessionsEmpty": String(localized: "supermux.harness.header.sessionsEmpty", defaultValue: "No sessions yet for this folder"),
            "supermux.harness.header.resume": String(localized: "supermux.harness.header.resume", defaultValue: "Resume"),
            "supermux.harness.header.fork": String(localized: "supermux.harness.header.fork", defaultValue: "Fork"),
            "supermux.harness.header.more": String(localized: "supermux.harness.header.more", defaultValue: "More"),
            "supermux.harness.header.compact": String(localized: "supermux.harness.header.compact", defaultValue: "Compact conversation"),
            "supermux.harness.header.clear": String(localized: "supermux.harness.header.clear", defaultValue: "Clear conversation"),
            "supermux.harness.header.export": String(localized: "supermux.harness.header.export", defaultValue: "Export transcript"),
            "supermux.harness.header.openTerminal": String(localized: "supermux.harness.header.openTerminal", defaultValue: "Open folder in terminal"),
            "supermux.harness.header.newSession": String(localized: "supermux.harness.header.newSession", defaultValue: "New session"),
            "supermux.harness.mode.default": String(localized: "supermux.harness.mode.default", defaultValue: "Ask each time"),
            "supermux.harness.mode.defaultShort": String(localized: "supermux.harness.mode.defaultShort", defaultValue: "Ask"),
            "supermux.harness.mode.acceptEdits": String(localized: "supermux.harness.mode.acceptEdits", defaultValue: "Auto-accept edits"),
            "supermux.harness.mode.acceptEditsShort": String(localized: "supermux.harness.mode.acceptEditsShort", defaultValue: "Auto-edit"),
            "supermux.harness.mode.plan": String(localized: "supermux.harness.mode.plan", defaultValue: "Plan only"),
            "supermux.harness.mode.planShort": String(localized: "supermux.harness.mode.planShort", defaultValue: "Plan"),
            "supermux.harness.mode.bypassPermissions": String(localized: "supermux.harness.mode.bypassPermissions", defaultValue: "Bypass all prompts"),
            "supermux.harness.mode.bypassPermissionsShort": String(localized: "supermux.harness.mode.bypassPermissionsShort", defaultValue: "Bypass"),
            "supermux.harness.divider.compact": String(localized: "supermux.harness.divider.compact", defaultValue: "Conversation compacted"),
            "supermux.harness.divider.compactTokens": String(localized: "supermux.harness.divider.compactTokens", defaultValue: "{tokens} tokens summarized"),
            "supermux.harness.divider.reset": String(localized: "supermux.harness.divider.reset", defaultValue: "Conversation cleared"),
            "supermux.harness.banner.dismiss": String(localized: "supermux.harness.banner.dismiss", defaultValue: "Dismiss"),
            "supermux.harness.banner.retryAttempt": String(localized: "supermux.harness.banner.retryAttempt", defaultValue: "Attempt {attempt} of {max}"),
            "supermux.harness.error.generic": String(localized: "supermux.harness.error.generic", defaultValue: "Something went wrong"),
            "supermux.harness.error.rateLimit": String(localized: "supermux.harness.error.rateLimit", defaultValue: "Usage limit reached"),
            "supermux.harness.error.billing": String(localized: "supermux.harness.error.billing", defaultValue: "Billing problem"),
            "supermux.harness.error.auth": String(localized: "supermux.harness.error.auth", defaultValue: "Authentication failed"),
            "supermux.harness.error.startFailed": String(localized: "supermux.harness.error.startFailed", defaultValue: "Could not start Claude"),
            "supermux.harness.a11y.transcript": String(localized: "supermux.harness.a11y.transcript", defaultValue: "Conversation transcript"),
            "supermux.harness.a11y.composer": String(localized: "supermux.harness.a11y.composer", defaultValue: "Message composer"),
            "supermux.harness.a11y.permissionAlert": String(localized: "supermux.harness.a11y.permissionAlert", defaultValue: "Claude needs permission to continue"),
            "supermux.harness.a11y.timeline": String(localized: "supermux.harness.a11y.timeline", defaultValue: "Conversation timeline"),
            "supermux.harness.time.seconds": String(localized: "supermux.harness.time.seconds", defaultValue: "{value}s"),
            "supermux.harness.time.minutes": String(localized: "supermux.harness.time.minutes", defaultValue: "{value}m {seconds}s"),
            "supermux.harness.time.hours": String(localized: "supermux.harness.time.hours", defaultValue: "{value}h {minutes}m"),
            "supermux.harness.time.justNow": String(localized: "supermux.harness.time.justNow", defaultValue: "just now"),
            "supermux.harness.time.minutesAgo": String(localized: "supermux.harness.time.minutesAgo", defaultValue: "{value}m ago"),
            "supermux.harness.time.hoursAgo": String(localized: "supermux.harness.time.hoursAgo", defaultValue: "{value}h ago"),
            "supermux.harness.time.daysAgo": String(localized: "supermux.harness.time.daysAgo", defaultValue: "{value}d ago"),
        ]
    }
}
