#!/usr/bin/env python3
"""Declarative ownership for the workflow-guard-tests Linux matrix.

Unknown paths deliberately return None so the caller can fail open to every
group. Keep this file data-oriented: tests compare STEP_OWNERS with ci-guards.yml
and verify directly executed paths route back to their owning group.
"""

from __future__ import annotations


GROUPS = (
    "preflight",
    "ci",
    "app-host-execution",
    "app-host-process",
    "app-host-cache",
    "release-ios",
    "release-notary",
    "release-tooling",
    "quality-sharding",
    "quality-runtime",
    "quality-determinism",
)

# Every step in workflow-guard-tests with an exact matrix.group condition.
# A step move or rename must update this table in the same change.
STEP_OWNERS = {
    "Initialize Ghostty for Zig version guard": "release-tooling",
    "Run canonical CMUX CI guard profile": "ci",
    "Test XCStrings catalog lint": "preflight",
    "Test macOS localization catalog tooling": "preflight",
    "Test review fabric contracts": "preflight",
    "Validate Blacksmith Testbox broker trust boundary": "ci",
    "Validate CI Xcode selection fast path": "release-notary",
    "Validate CI change area filter": "ci",
    "Validate CMUX INTERNAL main-push path filter": "release-ios",
    "Validate CMUX workload profile contract": "ci",
    "Validate Claude launch environment policy behavior": "preflight",
    "Validate Claude launch environment policy generation": "preflight",
    "Validate Computer Use helper notarization behavior": "release-notary",
    "Validate Ghostty Zig version synchronization": "release-tooling",
    "Validate Ghostty helper cache failure handling": "release-tooling",
    "Validate GhosttyKit checksum verification": "release-tooling",
    "Validate GhosttyKit release check behavior": "release-tooling",
    "Validate Localizable.xcstrings catalog structure": "preflight",
    "Validate Pro TestFlight distribution workflow": "release-ios",
    "Validate Python R2 appcast upload guard": "release-tooling",
    "Validate Python test harness syntax": "preflight",
    "Validate Release check architectures": "release-tooling",
    "Validate Sparkle appcast generation without previous archives": "release-notary",
    "Validate Sparkle delta finalization": "release-notary",
    "Validate Sparkle monotonic guard modes": "release-notary",
    "Validate Swift Testing suite timeout guard": "app-host-execution",
    "Validate Swift incremental diagnostics tooling": "preflight",
    "Validate Swift warning budget guard": "release-notary",
    "Validate TUI npm package artifact transfer": "preflight",
    "Validate TUI package artifact contract": "preflight",
    "Validate TestFlight notes generator": "release-ios",
    "Validate Xcode SourcePackages cache sanitizer": "app-host-cache",
    "Validate Xcode build metrics receipt": "ci",
    "Validate Xcode compilation cache pruning": "app-host-cache",
    "Validate Zig download resume and mirror isolation": "release-tooling",
    "Validate Zig install without sudo": "release-tooling",
    "Validate activation benchmark scrollback sizing": "ci",
    "Validate app bundle license compliance": "release-notary",
    "Validate app-host failure census": "app-host-process",
    "Validate app-host guard structure": "ci",
    "Validate app-host identity and cleanup confirmation": "app-host-process",
    "Validate app-host process receipts": "app-host-process",
    "Validate app-host test failure classification": "app-host-process",
    "Validate app-host user configuration isolation": "app-host-process",
    "Validate app-host xcodebuild attempt budget": "app-host-execution",
    "Validate app-host xcodebuild retry guard": "app-host-execution",
    "Validate auxiliary window close shortcut lint": "quality-determinism",
    "Validate bash prompt bootstrap composes with user PROMPT_COMMAND (starship)": "quality-determinism",
    "Validate bash shell integration job control": "quality-determinism",
    "Validate bundled-resource incremental outputs": "quality-runtime",
    "Validate checkout failure network diagnostics": "ci",
    "Validate cmux scheme test configuration": "app-host-cache",
    "Validate cmux-cloud-vm skill covers the vm CLI": "preflight",
    "Validate cmux-tui client installation": "release-tooling",
    "Validate cmuxTests sharding": "quality-sharding",
    "Validate control-plane generated types": "preflight",
    "Validate create-dmg version pinning": "release-notary",
    "Validate current GhosttyKit checksum pin": "release-tooling",
    "Validate dev-fleet warm-slot lifecycle": "preflight",
    "Validate docs deployment authentication guard": "preflight",
    "Validate embedded cmux.json schema generation": "preflight",
    "Validate external TestFlight group assignment helper": "release-ios",
    "Validate focused Dock shortcut routing guard": "quality-determinism",
    "Validate focused test launcher": "app-host-execution",
    "Validate iOS App Store lane identity": "release-ios",
    "Validate isolated app-host home cleanup": "app-host-process",
    "Validate local build cache preflight": "app-host-cache",
    "Validate local hook trust boundary": "ci",
    "Validate macOS runner guards": "preflight",
    "Validate manual iOS workflow ref resolution": "release-ios",
    "Validate markdown viewer asset compression": "release-notary",
    "Validate nightly Xcode selection": "release-notary",
    "Validate nightly notarization behavior": "release-notary",
    "Validate nightly prune Python compatibility": "release-tooling",
    "Validate nightly tag push auth": "release-notary",
    "Validate notification semantics gates": "ci",
    "Validate package test selection": "ci",
    "Validate persistent Mac compile admission contract": "preflight",
    "Validate pipe-safe CI capture": "app-host-execution",
    "Validate previous nightly build fetch": "release-notary",
    "Validate pull request caches are read-only": "ci",
    "Validate quality guard structure": "ci",
    "Validate release SDK build lane": "preflight",
    "Validate release asset guard": "release-notary",
    "Validate release bundle stripping": "release-notary",
    "Validate release does not gate on iOS screenshot capture": "release-ios",
    "Validate release guard structure": "ci",
    "Validate release tunnel extension identifiers": "release-ios",
    "Validate release-build timeout guard": "release-notary",
    "Validate reload shared DerivedData default": "preflight",
    "Validate required checks report for the merge queue": "ci",
    "Validate resumable GitHub release publication": "release-notary",
    "Validate reusable guard workflow structure": "ci",
    "Validate reusable workflow permission grants": "ci",
    "Validate selected iOS test execution guard": "app-host-cache",
    "Validate shallow complexity comparison fetching": "ci",
    "Validate sidebar extension point generation": "preflight",
    "Validate stale run cleanup eligibility": "ci",
    "Validate stalled GhosttyKit downloads resume": "release-tooling",
    "Validate tagged iOS device entitlement fallback": "release-ios",
    "Validate tagged reload works without the shared dev backend": "preflight",
    "Validate test compilation cache seeding": "quality-sharding",
    "Validate test determinism gate": "quality-determinism",
    "Validate the R2 cache store script": "ci",
    "Validate the trusted web complexity workflow": "ci",
    "Validate unit-test SwiftPM retry guard": "app-host-execution",
    "Validate universal nightly workflow": "release-notary",
    "Validate virtual display lock": "quality-runtime",
    "Validate xcodebuild failure diagnostics": "app-host-execution",
    "Validate xcodebuild noninteractive crash prompt guard": "app-host-execution",
}

# Direct executables plus known indirect inputs whose guard ownership is stable.
# Broad scanners below add their groups on top of these exact owners.
PATH_OWNERS = {
    ".github/review-fabric-policy.json": frozenset(("preflight",)),
    ".github/review-fabric.md": frozenset(("preflight",)),
    ".github/scripts/review_fabric.py": frozenset(("preflight",)),
    ".github/workflows/ios-testflight.yml": frozenset(("preflight", "ci", "release-ios")),
    "agent-chat/test/claude-environment.test.ts": frozenset(("preflight",)),
    "ghostty": frozenset(("release-tooling",)),
    "ios/scripts/upload-testflight.sh": frozenset(("release-ios",)),
    "ios/tests/tagged-device-entitlements.test.mjs": frozenset(("release-ios",)),
    "scripts/check-control-plane-types.sh": frozenset(("preflight",)),
    "scripts/check-test-determinism.py": frozenset(("quality-determinism",)),
    "scripts/ci/app_host_test_products.py": frozenset(("preflight",)),
    "scripts/ci/build_input_fingerprint.py": frozenset(("preflight",)),
    "scripts/ci/cmux_unit_test_shard.py": frozenset(("quality-sharding",)),
    "scripts/ci/cmux_workload_profile.py": frozenset(("ci",)),
    "scripts/ci/compile-app-host-test-product.sh": frozenset(("preflight",)),
    "scripts/ci/find_admitted_build.py": frozenset(("preflight",)),
    "scripts/ci/persistent_mac_route.py": frozenset(("preflight",)),
    "scripts/ci/product_input_identity.py": frozenset(("preflight",)),
    "scripts/ci/restore-app-host-test-product.sh": frozenset(("preflight",)),
    "scripts/ci/reuse_app_host_products.py": frozenset(("preflight",)),
    "scripts/ci/sanitize-xcode-source-packages-cache.py": frozenset(("preflight",)),
    "scripts/ci/swift_incremental_diagnostics.py": frozenset(("preflight",)),
    "scripts/generate-claude-launch-environment-policy.py": frozenset(("preflight",)),
    "scripts/generate-cmux-config-schema.py": frozenset(("preflight",)),
    "scripts/release_asset_guard.test.js": frozenset(("release-notary",)),
    "skills/cmux-cloud-vm/SKILL.md": frozenset(("preflight",)),
    "skills/cmux-cloud-vm/references/agent-workflows.md": frozenset(("preflight",)),
    "skills/cmux-cloud-vm/references/commands.md": frozenset(("preflight",)),
    "skills/cmux-cloud-vm/references/guest.md": frozenset(("preflight",)),
    "tests/test_app_bundle_license_compliance.sh": frozenset(("release-notary",)),
    "tests/test_app_host_test_products.py": frozenset(("ci",)),
    "tests/test_bash_integration_no_done_notifications.py": frozenset(("quality-determinism",)),
    "tests/test_benchmark_dev_fleet_warm_slots.py": frozenset(("preflight",)),
    "tests/test_build_app_bundled_resources.sh": frozenset(("quality-runtime",)),
    "tests/test_build_metrics.py": frozenset(("ci",)),
    "tests/test_ci_app_host_failure_census.py": frozenset(("app-host-process",)),
    "tests/test_ci_app_host_guard_structure.py": frozenset(("ci",)),
    "tests/test_ci_app_host_home_cleanup.sh": frozenset(("app-host-process",)),
    "tests/test_ci_app_host_home_isolation.py": frozenset(("app-host-process",)),
    "tests/test_ci_app_host_identity.sh": frozenset(("app-host-process",)),
    "tests/test_ci_app_host_pipe_capture.py": frozenset(("app-host-execution",)),
    "tests/test_ci_app_host_processes.sh": frozenset(("app-host-process",)),
    "tests/test_ci_app_host_test_output.py": frozenset(("app-host-process",)),
    "tests/test_ci_app_host_xcodebuild_attempts.sh": frozenset(("app-host-execution",)),
    "tests/test_ci_app_host_xcodebuild_retry.sh": frozenset(("app-host-execution",)),
    "tests/test_ci_auxiliary_window_close_shortcuts.sh": frozenset(("quality-determinism",)),
    "tests/test_ci_change_areas.py": frozenset(("ci",)),
    "tests/test_ci_checkout_network_diagnostics.py": frozenset(("ci",)),
    "tests/test_ci_cmux_unit_test_shard.py": frozenset(("quality-sharding",)),
    "tests/test_ci_create_dmg_pinned.sh": frozenset(("release-notary",)),
    "tests/test_ci_fetch_complexity_base.py": frozenset(("ci",)),
    "tests/test_ci_ghosttykit_checksum_present.sh": frozenset(("release-tooling",)),
    "tests/test_ci_ghosttykit_checksum_verification.sh": frozenset(("release-tooling",)),
    "tests/test_ci_ghosttykit_download_stall.sh": frozenset(("release-tooling",)),
    "tests/test_ci_ghosttykit_release_check.sh": frozenset(("release-tooling",)),
    "tests/test_ci_guard_workflow_structure.py": frozenset(("ci",)),
    "tests/test_ci_linux_guard_routing.py": frozenset(("ci",)),
    "tests/test_ci_merge_queue_required_checks.py": frozenset(("ci",)),
    "tests/test_ci_nightly_prune_python_compat.sh": frozenset(("release-tooling",)),
    "tests/test_ci_nightly_tag_push_auth.sh": frozenset(("release-notary",)),
    "tests/test_ci_nightly_xcode_selection.sh": frozenset(("release-notary",)),
    "tests/test_ci_notification_semantics.py": frozenset(("ci",)),
    "tests/test_ci_persistent_mac_compile.py": frozenset(("preflight",)),
    "tests/test_ci_product_publication.py": frozenset(("ci",)),
    "tests/test_ci_prune_xcode_compilation_cache.py": frozenset(("app-host-cache",)),
    "tests/test_ci_pull_request_caches_are_read_only.py": frozenset(("ci",)),
    "tests/test_ci_quality_guard_structure.py": frozenset(("ci",)),
    "tests/test_ci_r2_cache.sh": frozenset(("ci",)),
    "tests/test_ci_r2_upload_python.sh": frozenset(("release-tooling",)),
    "tests/test_ci_release_build_archs.sh": frozenset(("release-tooling",)),
    "tests/test_ci_release_build_timeout.sh": frozenset(("release-notary",)),
    "tests/test_ci_release_guard_structure.py": frozenset(("ci",)),
    "tests/test_ci_release_ios_screenshots_decoupled.sh": frozenset(("release-ios",)),
    "tests/test_ci_release_sdk_lane.sh": frozenset(("preflight",)),
    "tests/test_ci_release_tunnel_identifiers.sh": frozenset(("release-ios",)),
    "tests/test_ci_reusable_workflow_permissions.py": frozenset(("ci",)),
    "tests/test_ci_run_and_capture.sh": frozenset(("app-host-execution",)),
    "tests/test_ci_sanitize_xcode_source_packages_cache.py": frozenset(("app-host-cache",)),
    "tests/test_ci_scheme_testaction_debug.sh": frozenset(("app-host-cache",)),
    "tests/test_ci_select_package_tests.py": frozenset(("ci",)),
    "tests/test_ci_self_hosted_guard.sh": frozenset(("preflight",)),
    "tests/test_ci_swift_warning_budget.sh": frozenset(("release-notary",)),
    "tests/test_ci_test_compilation_cache_seed.sh": frozenset(("quality-sharding",)),
    "tests/test_ci_testbox_broker_guard.py": frozenset(("ci",)),
    "tests/test_ci_unit_test_spm_retry.sh": frozenset(("app-host-execution",)),
    "tests/test_ci_virtual_display_lock.sh": frozenset(("quality-runtime",)),
    "tests/test_ci_workload_profiles.py": frozenset(("ci",)),
    "tests/test_ci_xcode_selection_fast_path.sh": frozenset(("release-notary",)),
    "tests/test_ci_xcodebuild_noninteractive_helper.py": frozenset(("app-host-execution",)),
    "tests/test_ci_xcodebuild_with_diagnostics.sh": frozenset(("app-host-execution",)),
    "tests/test_cleanup_stale_runs.py": frozenset(("ci",)),
    "tests/test_cloud_vm_skill_coverage.py": frozenset(("preflight",)),
    "tests/test_compress_markdown_viewer_assets.sh": frozenset(("release-notary",)),
    "tests/test_dev_fleet_warm_slot.py": frozenset(("preflight",)),
    "tests/test_dock_shortcut_routing_guard.py": frozenset(("quality-determinism",)),
    "tests/test_docs_deploy_auth_guard.py": frozenset(("preflight",)),
    "tests/test_fetch_previous_nightly_dmgs.sh": frozenset(("release-notary",)),
    "tests/test_finalize_sparkle_deltas.sh": frozenset(("release-notary",)),
    "tests/test_ghostty_cli_helper_cache.sh": frozenset(("release-tooling",)),
    "tests/test_ghostty_zig_version_sync.sh": frozenset(("release-tooling",)),
    "tests/test_github_release_publication.py": frozenset(("release-notary",)),
    "tests/test_install_cmux_tui_client.sh": frozenset(("release-tooling",)),
    "tests/test_install_zig_ci_download_resume.sh": frozenset(("release-tooling",)),
    "tests/test_install_zig_ci_no_sudo.sh": frozenset(("release-tooling",)),
    "tests/test_ios_appstore_lane_identity.py": frozenset(("release-ios",)),
    "tests/test_ios_selected_test_execution.py": frozenset(("app-host-cache",)),
    "tests/test_ios_testflight_external_distribution.py": frozenset(("release-ios",)),
    "tests/test_ios_testflight_main_push_filter.py": frozenset(("release-ios",)),
    "tests/test_ios_testflight_notes.py": frozenset(("release-ios",)),
    "tests/test_ios_testflight_pro_distribution.py": frozenset(("release-ios",)),
    "tests/test_ios_workflow_dispatch_ref.py": frozenset(("release-ios",)),
    "tests/test_issue_5164_starship_prompt_composition.py": frozenset(("quality-determinism",)),
    "tests/test_lint_xcstrings.py": frozenset(("preflight",)),
    "tests/test_local_build_cache_policy.py": frozenset(("app-host-cache",)),
    "tests/test_local_build_cache_preflight.py": frozenset(("app-host-cache",)),
    "tests/test_localizable_xcstrings_structure.py": frozenset(("preflight",)),
    "tests/test_localization_catalog.py": frozenset(("preflight",)),
    "tests/test_localize_changes.py": frozenset(("preflight",)),
    "tests/test_nightly_universal_build.sh": frozenset(("release-notary",)),
    "tests/test_notarize_computer_use_helper.sh": frozenset(("release-notary",)),
    "tests/test_notarize_nightly_dmg.sh": frozenset(("release-notary",)),
    "tests/test_perf_activation_scrollback_sizing.py": frozenset(("ci",)),
    "tests/test_preflight_trust.py": frozenset(("ci",)),
    "tests/test_reload_local_backend_mode.sh": frozenset(("preflight",)),
    "tests/test_reload_shared_derived_data.sh": frozenset(("preflight",)),
    "tests/test_reuse_app_host_products.py": frozenset(("ci",)),
    "tests/test_review_fabric.py": frozenset(("preflight",)),
    "tests/test_run_e2e.py": frozenset(("app-host-execution",)),
    "tests/test_sparkle_build_monotonic_modes.sh": frozenset(("release-notary",)),
    "tests/test_sparkle_generate_appcast_no_deltas.sh": frozenset(("release-notary",)),
    "tests/test_strip_release_bundle.sh": frozenset(("release-notary",)),
    "tests/test_swift_incremental_diagnostics.py": frozenset(("preflight",)),
    "tests/test_swift_testing_suite_timeout.py": frozenset(("app-host-execution",)),
    "tests/test_tui_npm_package_artifact.py": frozenset(("preflight",)),
    "tests/test_tui_package_contract.py": frozenset(("preflight",)),
    "tests/test_web_complexity_trusted_workflow.py": frozenset(("ci",)),
    "tests/test_write_sidebar_extension_point.py": frozenset(("preflight",)),
}

# Changes here can alter which required work runs. They always exercise every
# group, including when the candidate implementation would route more narrowly.
ROUTING_POLICY_PATHS = frozenset({
    ".github/workflows/ci.yml",
    ".github/workflows/ci-guards.yml",
    "scripts/ci/detect_ci_change_areas.py",
    "scripts/ci/detect_linux_guard_changes.py",
    "scripts/ci/workflow_guard_groups.py",
    "tests/test_ci_change_areas.py",
    "tests/test_ci_linux_guard_routing.py",
    "tests/test_ci_guard_workflow_structure.py",
    "tests/test_ci_app_host_guard_structure.py",
    "tests/test_ci_quality_guard_structure.py",
    "tests/test_ci_release_guard_structure.py",
})

DETERMINISM_SUFFIXES = (".swift", ".py", ".sh", ".ts", ".tsx", ".js", ".mjs")


def _python_syntax_scan(path: str) -> bool:
    return path.endswith(".py") and path.startswith(("tests/", "tests_v2/", "scripts/"))


def _determinism_scan(path: str) -> bool:
    if not path.endswith(DETERMINISM_SUFFIXES):
        return False
    if path.startswith(("cmuxTests/", "cmuxUITests/", "ios/cmuxUITests/",
                        "tests/", "tests_v2/", "web/tests/", "webviews/test/")):
        return True
    return path.startswith("Packages/") and "/Tests/" in path


def groups_for_path(path: str) -> tuple[str, ...] | None:
    """Return current observers for path, or None when ownership is unknown."""
    if path in ROUTING_POLICY_PATHS:
        return GROUPS

    owners = set(PATH_OWNERS.get(path, ()))
    if _python_syntax_scan(path):
        owners.add("preflight")
    if _determinism_scan(path):
        owners.add("quality-determinism")

    if path == ".github/workflows/ios-testflight.yml":
        owners.update(("preflight", "ci"))

    if not owners:
        return None
    return tuple(group for group in GROUPS if group in owners)
