import type { ProtocolLine } from "../../protocol/types";
import {
  assistantText,
  assistantToolUse,
  initLine,
  initializeResponse,
  messageStart,
  resultLine,
  sessionState,
  statusLine,
  toolResult,
  userLine
} from "./build";

const MSG_A = "msg_resume_history_1";
const MSG_B = "msg_resume_history_2";

/**
 * Machine-authored records exactly as the CLI persists them (shapes verified
 * against real ~/.claude/projects JSONL): a caveat preamble, a slash-command
 * invocation, and its stdout. On resume these come back as plain user lines —
 * the round-5 screenshot was the pane drawing them as raw-XML chat bubbles.
 */
function diskUserText(content: string, extra: Record<string, unknown> = {}): ProtocolLine {
  return {
    type: "user",
    message: { role: "user", content },
    parent_tool_use_id: null,
    session_id: "resumed-session-4821",
    uuid: `disk-${Math.random().toString(16).slice(2)}`,
    ...extra
  } as ProtocolLine;
}

export const resumeHistory: ProtocolLine[] = [
  // Resuming still spawns a process, and the harness always performs the
  // `initialize` handshake on start — so the model catalog is present here just
  // as it is on a fresh session. Without it the header has no catalog to resolve
  // init's resolved model id against and the pill prints the raw id.
  initializeResponse(),
  initLine({ session_id: "resumed-session-4821" }),
  userLine("Why does the sidebar lose its scroll position when a workspace is restored?"),
  messageStart(MSG_A),
  assistantToolUse(MSG_A, "toolu_resume-read-1", "Read", {
    file_path: "/Users/dev/projects/supermux/Sources/SessionIndexView.swift"
  }),
  toolResult("toolu_resume-read-1", "     1\timport SwiftUI", {
    type: "text",
    file: {
      filePath: "/Users/dev/projects/supermux/Sources/SessionIndexView.swift",
      content: "import SwiftUI\n",
      numLines: 612,
      startLine: 1,
      totalLines: 612
    }
  }),
  assistantText(
    MSG_A,
    "Restore rebuilds the list identity: the `ForEach` is keyed on the panel object rather than a stable id, so SwiftUI treats every row as new and resets the scroll offset."
  ),
  resultLine({
    result: "The ForEach identity changes on restore, resetting scroll offset.",
    num_turns: 2,
    total_cost_usd: 0.0412
  }),
  userLine("Fix it."),
  messageStart(MSG_B),
  assistantToolUse(MSG_B, "toolu_resume-edit-1", "Edit", {
    file_path: "/Users/dev/projects/supermux/Sources/SessionIndexView.swift",
    old_string: "ForEach(panels, id: \\.self)",
    new_string: "ForEach(panels, id: \\.stableID)"
  }),
  toolResult("toolu_resume-edit-1", "Edited.", {
    filePath: "/Users/dev/projects/supermux/Sources/SessionIndexView.swift",
    userModified: false,
    structuredPatch: [
      {
        oldStart: 188,
        oldLines: 4,
        newStart: 188,
        newLines: 4,
        lines: [
          "     LazyVStack(spacing: 0) {",
          "-        ForEach(panels, id: \\.self) { panel in",
          "+        ForEach(panels, id: \\.stableID) { panel in",
          "             SessionRow(snapshot: panel.snapshot)"
        ]
      }
    ]
  }),
  assistantText(
    MSG_B,
    "Keyed the `ForEach` on `stableID`, which survives restore. Scroll position now persists across a workspace reload."
  ),
  resultLine({
    result: "Keyed the ForEach on stableID; scroll position survives restore.",
    num_turns: 2,
    total_cost_usd: 0.0863
  }),
  // The user ran /model mid-session. Renders as a quiet command chip with a dim
  // stdout line; the caveat record renders as nothing at all.
  diskUserText(
    "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>",
    { isMeta: true }
  ),
  diskUserText(
    "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus[1m]</command-args>"
  ),
  diskUserText(
    "<local-command-stdout>Set model to opus[1m] (claude-opus-5[1m])</local-command-stdout>"
  )
];

export const resumeFixture: ProtocolLine[] = [
  ...resumeHistory,
  initLine({ session_id: "resumed-session-4821" }),
  userLine("Add a regression test for that."),
  sessionState("running"),
  statusLine("requesting"),
  messageStart("msg_resume_live"),
  assistantText(
    "msg_resume_live",
    "Adding `SessionIndexScrollRestoreTests` that snapshots the offset, triggers a restore, and asserts the offset is unchanged."
  ),
  statusLine(null),
  resultLine({ result: "Added SessionIndexScrollRestoreTests." })
];
