//! Per-user autostart integration for the relay.
use std::{fs,io::Write,path::{Path,PathBuf},process::Command as ProcessCommand,time::{SystemTime,UNIX_EPOCH}};
const LABEL:&str="com.chatmux.relay";
fn home()->Result<PathBuf,String>{std::env::var_os("HOME").map(PathBuf::from).ok_or_else(||"HOME is not set".into())}
fn xml_escape(v:&str)->String{v.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;").replace('"',"&quot;").replace('\'',"&apos;")}
fn shell_quote(v:&str)->String{format!("'{}'",v.replace('\'',"'\\''"))}
fn atomic_write(p:&Path,b:&str)->Result<(),String>{let d=p.parent().ok_or("autostart path has no parent")?;fs::create_dir_all(d).map_err(|e|e.to_string())?;let n=SystemTime::now().duration_since(UNIX_EPOCH).map_err(|e|e.to_string())?.as_nanos();for i in 0..16{let t=d.join(format!(".autostart-{}-{}",std::process::id(),n+i));match fs::OpenOptions::new().write(true).create_new(true).open(&t){Ok(mut f)=>{#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;fs::set_permissions(&t,fs::Permissions::from_mode(0o600)).map_err(|e|e.to_string())?;}f.write_all(b).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())?;drop(f);let r=fs::rename(&t,p).map_err(|e|e.to_string());if r.is_err(){let _=fs::remove_file(&t);}return r},Err(e)if e.kind()==std::io::ErrorKind::AlreadyExists=>continue,Err(e)=>return Err(e.to_string())}}Err("could not create a unique temporary autostart file".into())}
fn run(p:&str,a:&[&str])->Result<(),String>{let s=ProcessCommand::new(p).args(a).status().map_err(|e|format!("run {p}: {e}"))?;s.success().then_some(()).ok_or_else(||format!("{p} failed with {s}"))}
#[cfg(target_os="macos")]fn install_impl(e:&Path)->Result<String,String>{let p=home()?.join("Library/LaunchAgents").join(format!("{LABEL}.plist"));let x=e.to_str().ok_or("executable path is not valid UTF-8")?;let b=format!("<?xml version=\"1.0\"?><plist version=\"1.0\"><dict><key>Label</key><string>{LABEL}</string><key>ProgramArguments</key><array><string>{}</string><string>--no-onboard</string></array><key>RunAtLoad</key><true/><key>KeepAlive</key><true/></dict></plist>\n",xml_escape(x));atomic_write(&p,&b)?;let d=format!("gui/{}",unsafe{libc::getuid()});let s=p.to_str().ok_or("autostart path is not valid UTF-8")?;let _=run("launchctl",&["bootout",&d,s]);run("launchctl",&["bootstrap",&d,s])?;Ok(format!("installed {}",p.display()))}
#[cfg(target_os="linux")]fn install_impl(e:&Path)->Result<String,String>{let p=home()?.join(".config/systemd/user/chatmux-relay.service");let x=e.to_str().ok_or("executable path is not valid UTF-8")?;atomic_write(&p,&format!("[Unit]\nDescription=chatmux relay\n[Service]\nExecStart={} --no-onboard\nRestart=on-failure\nRestartSec=5\n[Install]\nWantedBy=default.target\n",shell_quote(x)))?;run("systemctl",&["--user","daemon-reload"])?;run("systemctl",&["--user","enable","--now","chatmux-relay.service"])?;Ok(format!("installed {}",p.display()))}
#[cfg(target_os="windows")]fn install_impl(e:&Path)->Result<String,String>{let x=e.to_str().ok_or("executable path is not valid UTF-8")?;run("schtasks",&["/Create","/F","/SC","ONLOGON","/TN",LABEL,"/TR",&format!("\"{}\" --no-onboard",x)])?;run("schtasks",&["/Run","/TN",LABEL])?;Ok(format!("installed Windows task {LABEL}"))}
#[cfg(not(any(target_os="macos",target_os="linux",target_os="windows")))]fn install_impl(_: &Path)->Result<String,String>{Err("autostart is unsupported on this platform".into())}
pub fn install(e:&Path)->Result<String,String>{install_impl(e)}
pub fn uninstall()->Result<String,String>{#[cfg(target_os="macos")]{{let p=home()?.join("Library/LaunchAgents").join(format!("{LABEL}.plist"));let d=format!("gui/{}",unsafe{libc::getuid()});if let Some(s)=p.to_str(){let _=run("launchctl",&["bootout",&d,s]);}if let Err(e)=fs::remove_file(&p){if e.kind()!=std::io::ErrorKind::NotFound{return Err(e.to_string())}}return Ok(format!("removed {}",p.display()));}}#[cfg(target_os="linux")]{{let p=home()?.join(".config/systemd/user/chatmux-relay.service");let _=run("systemctl",&["--user","disable","--now","chatmux-relay.service"]);if let Err(e)=fs::remove_file(&p){if e.kind()!=std::io::ErrorKind::NotFound{return Err(e.to_string())}}let _=run("systemctl",&["--user","daemon-reload"]);return Ok(format!("removed {}",p.display()));}}#[cfg(target_os="windows")]{{let _=run("schtasks",&["/Delete","/F","/TN",LABEL]);return Ok(format!("removed Windows task {LABEL}"));}}Err("autostart is unsupported on this platform".into())}
#[cfg(test)]mod tests{use super::*;#[test]fn escapes(){assert_eq!(xml_escape("a<&\"' >"),"a&lt;&amp;&quot;&apos; &gt;");}#[test]fn quotes(){assert_eq!(shell_quote("/tmp/a'b"),"'/tmp/a'\\''b'");}}
